### ISSUE TITLE
EAS Error: Invalid `Podfile` file: cannot load such file -- /Users/expo/workingdir/build/node_modules/expo-modules-autolinking/scripts/ios/xcode_env_generator

### ISSUE THREAD

**Issue by hrougier** [expo/eas-cli#1251]
### Summary

Using `eas-cli@0.57.0` and `yarn@3.2.2` with workspaces, packages are hoisted in the top level `node_modules` of the monorepo.

There is a version conflict of `expo-modules-autolinking` between:
- `node_modules/eas-cli/node_modules/@expo/prebuild-config/package.json` having `expo-modules-autolinking@~0.5.1` as a dependency
- `node_modules/expo/package.json` having `expo-modules-autolinking@0.10.1` as a dependency

So the top level hoisted version of `expo-modules-autolinking` is 0.5.x because of:
- `eas-cli/package.json` ->  `@expo/prebuild-config@3.1.6` -> `expo-modules-autolinking@~0.5.1`
- while other expo packages use latest `@expo/prebuild-config@5` -> `expo-modules-autolinking >= 0.8.1` (peer dependency)

`eas build` crashes during the _Install pods_ step with the following error message:
```
Installing pods
[!] Invalid `Podfile` file: cannot load such file -- /Users/expo/workingdir/build/node_modules/expo-modules-autolinking/scripts/ios/xcode_env_generator.
 #  from /Users/expo/workingdir/build/mobile/app/ios/Podfile:1
 #  -------------------------------------------
 >  require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
 #  require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
 #  -------------------------------------------
pod exited with non-zero code: 1
```
because of `expo-modules-autolinking@0.5.x` not containing any `xcode_env_generator` script.

Quick solution:

Adding a [resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) in the top level `package.json` of the monorepo:

```
"resolutions": {
  "@expo/config-plugins": "~5.0.0",
  "@expo/prebuild-config": "~5.0.0",
  "expo-modules-autolinking": "0.10.1"
}
```

So the top level hoisted version of `expo-modules-autolinking` is forced to 0.10.1.

Edit: same fix for `@expo/config-plugins` and `@expo/prebuild-config` after running `expo-cli doctor`.

### Managed or bare?

managed

### Environment

`npx expo-env-info`

```
expo-env-info 1.0.5 environment info:
  System:
    OS: macOS 12.3
    Shell: 5.8 - /bin/zsh
  Binaries:
  Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.2.2 - ~/.nvm/versions/node/v16.16.0/bin/yarn
  npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  SDKs:
  iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
  IDEs:
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Expo Workflow: managed
```

`expo-cli doctor`

```
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.4
  @expo/config-plugins@4.0.18
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^5.0.1
Found invalid:
  @expo/prebuild-config@3.1.6
  (for more info, run: npm why @expo/prebuild-config)
```

### Reproducible demo or steps to reproduce from a blank project

[https://docs.expo.dev/guides/monorepos/](https://docs.expo.dev/guides/monorepos/)

**Comment by felpsio** [comment]
I'm having the same problem. Thanks for the quick solution

**Comment by hrougier** [comment]
This has been fixed by release 0.59.0 of eas-cli thanks to PR #1262 so the `resolutions` field is no longer needed!

**Comment by haveamission** [comment]
@hrougier Any additional steps needed? I upgraded my eas-cli to the latest version (like 3.10) now, and I'm still getting the error when running `npx expo run:ios`

**Comment by Ayu360** [comment]
Thanks man, could'nt even imagine adding:
"resolutions": {
  "@expo/config-plugins": "~5.0.0",
  "@expo/prebuild-config": "~5.0.0",
  "expo-modules-autolinking": "0.10.1"
}

This much in package.json will resolve everything!!
