### ISSUE TITLE
Starting with eas-cli@2.2.0 eas build returns error "Error: Input is required, but stdin is not readable"

### ISSUE THREAD

**Issue by sean-m-oleary** [expo/eas-cli#1470]
### Summary

We are running eas build using the following command:

npx eas-cli build --profile=test --non-interactive --platform=all

And i get the following error starting only with eas-cli@2.2.0. It does NOT happen with eas-cli@2.1.0

Error: Input is required, but stdin is not readable.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=71&linesState=71)
      System:
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=72&linesState=72)
        OS: Windows 10 10.0.17763
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=73&linesState=73)
      Binaries:
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=74&linesState=74)
        Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=75&linesState=75)
        Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=76&linesState=76)
        npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=77&linesState=77)
      npmPackages:
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=78&linesState=78)
        @expo/webpack-config: ~0.16.21 => 0.16.23
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=79&linesState=79)
        babel-preset-expo: ~9.1.0 => 9.1.0
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=80&linesState=80)
        expo: ^45.0.0 => 45.0.2
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=81&linesState=81)
        react: 17.0.2 => 17.0.2
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=82&linesState=82)
        react-dom: 17.0.2 => 17.0.2
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=83&linesState=83)
        react-native: 0.68.2 => 0.68.2
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=84&linesState=84)
        react-native-web: 0.17.7 => 0.17.7
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=85&linesState=85)
      Expo Workflow: managed

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with expo-cli on Windows. You may encounter issues using cmd.exe.
[14:41:09](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=88&linesState=88)
  
[14:41:10](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=89&linesState=89)
  [14:41:10] Some dependencies are incompatible with the installed expo package version:
[14:41:10](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=90&linesState=90)
  [14:41:10]  - expo-dev-client - expected version: ~1.0.1 - actual version installed: 1.0.0
[14:41:10](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=91&linesState=91)
  [14:41:10]  - expo-notifications - expected version: ~0.15.4 - actual version installed: 0.15.3
[14:41:10](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=92&linesState=92)
  [14:41:10]  - expo-updates - expected version: ~0.13.4 - actual version installed: 0.13.2
[14:41:10](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=93&linesState=93)
  [14:41:10] Your project may not work correctly until you install the correct versions of the packages.
[14:41:10](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=94&linesState=94)
  To install the correct versions of these packages, please run: expo doctor --fix-dependencies,
[14:41:10](https://delta-tcs-1:8082/buildConfiguration/ContinuousDelivery_Smarthub_SmarthubTestBuild_BuildSmarthubEas/737359?buildTab=log&focusLine=95&linesState=95)
  or install individual packages by running expo install [package-name ...]

### Error output

Error: Input is required, but stdin is not readable.

### Reproducible demo or steps to reproduce from a blank project

na

**Comment by dsokal** [comment]
Duplicated issue https://github.com/expo/eas-cli/issues/1424

**Comment by sean-m-oleary** [comment]
Is it resolved in the latest version?

Thanks
Sean
________________________________
From: Dominik Sokal ***@***.***>
Sent: Wednesday, October 26, 2022 9:50:14 AM
To: expo/eas-cli ***@***.***>
Cc: Sean O'Leary ***@***.***>; Author ***@***.***>
Subject: [External]Re: [expo/eas-cli] Starting with ***@***.*** eas build returns error "Error: Input is required, but stdin is not readable" (Issue #1470)


Closed #1470<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fexpo%2Feas-cli%2Fissues%2F1470&data=05%7C01%7Csoleary%40venterra.com%7Cbff2815cce7b435647aa08dab759026d%7Ce22aea6d0cf848038e12edaecd4fa3f2%7C0%7C0%7C638023890194510188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=89GRAjeALpzSw7yPszRAt6n26kTcQz1Xj6it%2BjVVT%2Fs%3D&reserved=0> as completed.

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fexpo%2Feas-cli%2Fissues%2F1470%23event-7673063964&data=05%7C01%7Csoleary%40venterra.com%7Cbff2815cce7b435647aa08dab759026d%7Ce22aea6d0cf848038e12edaecd4fa3f2%7C0%7C0%7C638023890194510188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y6HNPxQt05fZsld%2FJ4U1%2BaFKbQymtShnd%2B%2BKbHXC6JI%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAYXDBLHWEJFCMFAVD7M4PTWFEZJNANCNFSM6AAAAAARLNLG2Y&data=05%7C01%7Csoleary%40venterra.com%7Cbff2815cce7b435647aa08dab759026d%7Ce22aea6d0cf848038e12edaecd4fa3f2%7C0%7C0%7C638023890194510188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZKuoWMaUQktKfI1jzXhmrktTK2MsjJFmXfaYEioaKMQ%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

This email is from an external sender.
DO NOT click links, open attachments, or provide sensitive information if the sender is unknown.

**Comment by dsokal** [comment]
Yes, it should be fixed in the latest version.

**Comment by HarbinLc2014** [comment]
Hi I'm still getting this error after upgrading to eas-cli 2.7.0. 

the version on CI is:

expo-updates@0.15.5
expo-cli@6.0.8
eas-cli@2.7.0

Error message : 

2022-11-14T23:53:19.9045691Z Error: Command failed: npx eas-cli build -p android --no-wait --non-interactive --profile production
2022-11-14T23:53:19.9047510Z npx: installed 353 in 16.772s
2022-11-14T23:53:19.9058300Z     Error: Input is required, but stdin is not readable.
2022-11-14T23:53:19.9058697Z 
2022-11-14T23:53:19.9059371Z     at ChildProcess.exithandler (node:child_process:402:12)
2022-11-14T23:53:19.9060673Z     at ChildProcess.emit (node:events:513:28)
2022-11-14T23:53:19.9061925Z     at ChildProcess.emit (node:domain:489:12)
2022-11-14T23:53:19.9062718Z     at maybeClose (node:internal/child_process:1100:16)
2022-11-14T23:53:19.9063608Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
2022-11-14T23:53:19.9064385Z   code: 1,
2022-11-14T23:53:19.9065047Z   killed: false,
2022-11-14T23:53:19.9065827Z   signal: null,
2022-11-14T23:53:19.9067065Z   cmd: 'npx eas-cli build -p android --no-wait --non-interactive --profile production'
2022-11-14T23:53:19.9068000Z }
2022-11-14T23:53:19.9110156Z ##[error]Error: The process '/usr/bin/bash' failed with exit code 1
2022-11-14T23:53:19.9123939Z ##[section]Finishing: Run Release Script


Please take a look thanks

**Comment by Daniel-Cross** [comment]
Also getting the same issue on eas-cli/3.3.2 darwin-x64 node-v16.17.0

Error: Input is required, but stdin is not readable. Failed to display 
Error: Process completed with exit code 1.
