### ISSUE TITLE
eas-cli@6.1.0 Updates_1.getRuntimeVersionNullable is not function

### ISSUE THREAD

**Issue by TVGSOFT** [expo/eas-cli#2190]
### Summary

Discovered @expo/build-tools@1.0.59 was used a broken function by @expo/config-plugins@7.8.4

@expo/config-plugins@7.8.4: only provide Updates.getRuntimeVersionNullableAsync, but  @expo/build-tools@1.0.59 used Updates.getRuntimeVersionNullable

### Managed or bare?

Bare

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 32, 33, 34
        Build Tools: 26.0.2, 28.0.3, 29.0.2, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0, 34.0.0
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.21 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.9.3
    Expo Workflow: bare

### Error output

Run "eas build -p android --profile production --local" then got an error as below:
Updates_1.getRuntimeVersionNullable is not function

### Reproducible demo or steps to reproduce from a blank project

- Install eas-cli@6.1.0
- Run "eas build -p android --profile production --local"
- Even downgrade to "eas-cli@5.9.3" but can not force to downgrade @expo/config-plugins"

**Comment by szdziedzic** [comment]
yeah looks like a real issue, thanks for reporting it!

**Comment by szdziedzic** [comment]
working on a fix

**Comment by szdziedzic** [comment]
it should be fixed in the new `latest` version (7.0.0)

**Comment by szdziedzic** [comment]
let me know if it works for you

**Comment by wodin** [comment]
Thanks for the super fast fix!

It works for me and another two people on this thread:
https://discord.com/channels/695411232856997968/1197801476345565327/1197921854493573141

**Comment by mlsm-trl** [comment]
For me, eas 7.0.0 worked!

**Comment by szdziedzic** [comment]
Ok, so I'm closing the issue. Thanks! 🎉

**Comment by maniteja-emmadi** [comment]
Thanks for resolving it, I was also facing the same issue 👍

**Comment by scottgrunerud** [comment]
Absolute legends for fixing this so quickly thank you 🔥

**Comment by leaftail1880** [comment]
For anyone who still facing this issue with eas-cli installed globally via yarn
![img](https://github.com/expo/eas-cli/assets/110915645/ec09bf84-2365-4a8c-8aca-7530fcbf8ac0)

Just 
```bash
yarn global remove eas-cli
npm -g i eas-cli
``` 
For me, this fixed an issue 👍

**Comment by chiefchief** [comment]
i still facing this issue with local build - `eas build --platform ios --local`

**Comment by YolandaRib-4** [comment]
@chiefchief, I encountered the same error in version 7.3.0 and experimented with earlier versions. Eventually, I discovered that I had eas-cli installed both locally and globally. By removing the local version and downgrading to version 7.2.0, I managed to resolve the issue. However, I'm uncertain whether the fix resulted from the downgrade or the removal of the local CLI. I hope this helps

**Comment by chrisbruford** [comment]
I also hit this issue on `7.3.0` installed globally using yarn. Resolved by following the documentation and using `npx eas-cli@latest`

I wonder what the limitation is in not being able to handle running this with yarn.

**Comment by Durotemy** [comment]
TypeError: (0 , _updates).getRuntimeVersionNullable is not a function
still getting this error.
when i do yarn global remove eas-cli it says "No package 'eas-cli' found to uninstall"

so i do a npm -g i eas-cli and it install

but this error still persist

**Comment by leaftail1880** [comment]
> TypeError: (0 , _updates).getRuntimeVersionNullable is not a function still getting this error. when i do yarn global remove eas-cli it says "No package 'eas-cli' found to uninstall"
> 
> so i do a npm -g i eas-cli and it install
> 
> but this error (TypeError: (0 , _updates).getRuntimeVersionNullable is not a function)
> 
> still persist

Try uninstalling it globally and then using `npx eas-cli@latest`

**Comment by Durotemy** [comment]
when i tried installing got this

**Comment by ullaskunder1** [comment]
why this is issue is close is this issue resolved ?

**Comment by wodin** [comment]
> so i do a npm -g i eas-cli and it install

You should not install it as a dependency of your app. It should be installed globally

**Comment by wodin** [comment]
> when i do yarn global remove eas-cli it says "No package 'eas-cli' found to uninstall"

Make sure you don't have it installed in some other way. e.g. by `npm` instead of `yarn` or somewhere else in your `PATH`.

Maybe search your whole computer for `eas`. Uninstall it if you find it.

Then install it globally with `npm i -g eas-cli`.
Then make sure it's in your `PATH`.

**Comment by wodin** [comment]
> why this is issue is close is this issue resolved ?

As long as you're using the latest version of `eas-cli`, this issue should be resolved.
