### ISSUE TITLE
`Authentication with Apple Developer Portal failed!`

### ISSUE THREAD

**Issue by ekorman** [expo/eas-cli#2224]
### Summary

I get the error

```
Authentication with Apple Developer Portal failed!
Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
    Error: build command failed.
```

when running `eas build --profile preview --platform ios`. this command worked successfully a few days ago

### Managed or bare?

managed

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
      Watchman: 2023.10.30.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ~49.0.15 => 49.0.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 7.1.3
    Expo Workflow: managed
```

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### Error output

```
Authentication with Apple Developer Portal failed!
Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
    at M.setCookie (/Users/eric/.nvm/versions/node/v16.20.0/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:927590)
    at M.setCookie (/Users/eric/.nvm/versions/node/v16.20.0/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:697286)
    at /Users/eric/.nvm/versions/node/v16.20.0/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:894766
    at new Promise (<anonymous>)
    at /Users/eric/.nvm/versions/node/v16.20.0/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:894571
    at Object.apply (/Users/eric/.nvm/versions/node/v16.20.0/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:895502)
    at /Users/eric/.nvm/versions/node/v16.20.0/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:868909
    at Array.forEach (<anonymous>)
    at c (/Users/eric/.nvm/versions/node/v16.20.0/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:868881)
    at /Users/eric/.nvm/versions/node/v16.20.0/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:867223
    Error: build command failed.
```

### Reproducible demo or steps to reproduce from a blank project

Run
```
eas build --profile preview --platform ios
```

**Comment by Niravpatel129** [comment]
+1 having this issue too

**Comment by alantvu** [comment]
also having this issue

**Comment by baristikir** [comment]
I'm facing the same issue stated here, builds for ios platform were working fine a few days ago but are breaking today all of sudden...

**Comment by mthomas100** [comment]
Suddenly having this issue too when running `eas build --profile development --platform ios`

**Comment by vbpns** [comment]
+1

**Comment by afsadilson** [comment]
++1

**Comment by frechg** [comment]
+1, Building with no issues yesterday.

**Comment by eudiegosilva** [comment]
+++1

**Comment by timohaver** [comment]
+1

```
EAS CLI 7.1.3 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      npm: 10.4.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Utilities:
      Git: 2.39.3 - /usr/bin/git
    npmPackages:
      expo: ~50.0.5 => 50.0.6 
      expo-dev-client: ~3.3.8 => 3.3.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.1.3
    Project workflow: managed
```

**Comment by Jonatthu** [comment]
Same here with latest eas-cli

**Comment by AmitayCohen1** [comment]
Same

**Comment by strbavaclav** [comment]
+1

**Comment by hassanzeaiter** [comment]
Same

**Comment by awwbaw3** [comment]
Same

**Comment by mikeRChambers610** [comment]
+1

**Comment by lukas-sitkauskas** [comment]
+1

**Comment by vitor-rmcosta** [comment]
Same here

**Comment by MaheshtheDev** [comment]
I am facing same issue too all of the sudden!

**Comment by danielgolan** [comment]
+1

**Comment by meerbex** [comment]
The same issue here

**Comment by druckhead** [comment]
Having the same issue

**Comment by gustavoelizalde** [comment]
Same issue here

```
VERSION
eas-cli/7.1.3 darwin-x64 node-v18.18.2
```

**Comment by export-mike** [comment]
same here +1

**Comment by MariuzM** [comment]
Same, was working fine 2 days ago

**Comment by brentvatne** [comment]
thanks, we will investigate this.

you can use `eas build --non-interactive` to skip the apple auth prompt and used stored app signing credentials to work around this issue for now.

i'll lock the issue for now so that this comment is easily discoverable, and we'll follow up shortly.

**Comment by brentvatne** [comment]
fixed in eas-cli@7.2.0 - please update to this version. there was a change on the apple api server side, and this new eas-cli version accounts for this change.

**Comment by MariuzM** [comment]
Thank you, worked great for old and new projects

**Comment by rei-shaholli** [comment]
Awesome works !!!

**Comment by penicillin0** [comment]
> eas-cli@7.2.0 で修正されました - このバージョンに更新してください。Apple API サーバー側に変更があり、この新しい eas-cli バージョンはこの変更を反映しています。

This works for me! Thank you!

**Comment by rsnr** [comment]
> fixed in eas-cli@7.2.0 - please update to this version. there was a change on the apple api server side, and this new eas-cli version accounts for this change.

I uninstalled eas-cli and reinstalled eas-cli@7.2.0 . Unfortunately I'm still getting the same error upon running eas build --profile staging --platform ios .
Tried adding `--clear-cache` but it doesn't help.

**Comment by MariuzM** [comment]
> @brentvatne
> 
> > fixed in eas-cli@7.2.0 - please update to this version. there was a change on the apple api server side, and this new eas-cli version accounts for this change.
> 
> I uninstalled eas-cli and reinstalled eas-cli@7.2.0 . Unfortunately I'm still getting the same error upon running eas build --profile staging --platform ios . Tried adding `--clear-cache` but it doesn't help.

can you try `eas --version` what version it shows? 
also `where eas`

**Comment by rsnr** [comment]
> > @brentvatne
> > > fixed in eas-cli@7.2.0 - please update to this version. there was a change on the apple api server side, and this new eas-cli version accounts for this change.
> > 
> > 
> > I uninstalled eas-cli and reinstalled eas-cli@7.2.0 . Unfortunately I'm still getting the same error upon running eas build --profile staging --platform ios . Tried adding `--clear-cache` but it doesn't help.
> 
> can you try `eas --version` what version it shows? also `where eas`
> 
> also try in `eas` file adding
> 
> ```
>   "cli": {
>     "version": ">= 7.2.0",
>   },
> ```

eas --version returns: eas-cli/7.2.0 darwin-arm64 node-v18.18.0
I added "cli": {  "version": ">= 7.2.0"  } and it works! 
Thank you.

**Comment by andersonmiranda-com** [comment]
I had the same issue. Reinstalling eas-cli worked for me:

`npm install -g eas-cli`

**Comment by mthomas100** [comment]
> > @brentvatne
> > > fixed in eas-cli@7.2.0 - please update to this version. there was a change on the apple api server side, and this new eas-cli version accounts for this change.
> > 
> > 
> > I uninstalled eas-cli and reinstalled eas-cli@7.2.0 . Unfortunately I'm still getting the same error upon running eas build --profile staging --platform ios . Tried adding `--clear-cache` but it doesn't help.
> 
> can you try `eas --version` what version it shows? also `where eas`
> 
> also try in `eas` file adding
> 
> ```
>   "cli": {
>     "version": ">= 7.2.0",
>   },
> ```

`npm install -g eas-cli` in combination with this eas.json change resolved the issue for me

**Comment by ChristopherBanas** [comment]
This is why I love expo, thank you for the fast work

**Comment by hsiez** [comment]
Not sure if this is helpful but the same issue happened last year in feb too

**Comment by brteller** [comment]
Not sure if anyone else is having this issue, but whenever I grab the latest version it constantly reverts back to the previous version. I see someone had a similar issue, but forcing it in eas.json did not work for me as the global dependency doesn't appear to be updating past the previous version. I've tried to upgrade it globally through yarn and npm using sudo and no luck. Curious if anyone else is having trouble grabbing version 7.2.0 from 7.1.2

**Comment by guillaumegaluz** [comment]
Thanks @brentvatne!

**Comment by hassanzeaiter** [comment]
> Same

I updated eas-cli again and it's working now.

**Comment by fabioglimb** [comment]
Still not working after updating eas-cli@7.2.0 and specifying the version in eas.json file

**Comment by TomasSestak** [comment]
7.2.0 works perfectly

**Comment by alberttsg** [comment]
yarn global add eas-cli

**Comment by fabioglimb** [comment]
In my specific case, the authentication flow with Apple works, but if I'm trying to create a build for an identifier which has an expired or missing Distribution Certificate/Provisioning Profile, it gives me an error. The request to Apple Developer seems to fail because the files aren't created on the Apple Developer section.

I even tried deleting the Apple authentication cookie saved locally and logging in again; the authentication flow and team selection works fine.

Meanwhile, I solved the issue by uploading directly on the Expo Dashboard the Distribution Certificate (or selecting another one) and Provisioning Profile. If someone has encountered the same error and knows how to solve it, it would be appreciated.

**Comment by HakanPuente** [comment]
I have `eas-cli/7.2.0,` but it still giving 
```
Authentication with Apple Developer Portal failed!
Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
    Error: build command failed.
```

**Comment by upstrive** [comment]
+1

**Comment by pera14** [comment]
+1

**Comment by ramisalem** [comment]
what work for me and it's so strange is 
- reinstall eas yarn global add eas-cli 
- remove it npm uninstall -g eas-cli 
- reinstall  again yarn global add eas-cli 


Might help someone

**Comment by pera14** [comment]
> what work for me and it's so strange is
> 
> * reinstall eas yarn global add eas-cli
> * remove it npm uninstall -g eas-cli
> * reinstall  again yarn global add eas-cli
> 
> Might help someone

This didn't work for me, however, I reinstalled npm global eas-cli:

```
npm uninstall -g eas-cli
npm install -g eas-cli
```
after that I just reinstalled node_modules and it worked for me

**Comment by amamenko** [comment]
My version of `eas-cli` wasn't updating due to using `nvm` to manage multiple Node versions:

```
% which eas
/Users/current/.nvm/versions/node/v16.17.0/bin/eas

% node -v
v20.10.0

% nvm use v20.10.0
Now using node v20.10.0 (npm v10.2.3)

% which eas
/Users/current/.nvm/versions/node/v20.10.0/bin/eas

% npm install -g eas-cli
changed 408 packages in 5s

38 packages are looking for funding
  run `npm fund` for details
  
% eas -v
eas-cli/7.2.0 darwin-arm64 node-v20.10.0
```

Make sure you are installing `eas-cli` while using the correct Node version.

**Comment by amitchaudhary140** [comment]
7.2.0 works fine.

**Comment by pera14** [comment]
I'm not sure if it's relevant here, but since I moved to 7.2.0 I'm having this issue on build:

```
/Users/expo/workingdir/build/node_modules/cliui/build/index.cjs:291
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/expo/workingdir/build/node_modules/string-width/index.js from /Users/expo/workingdir/build/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /Users/expo/workingdir/build/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/cliui/build/index.cjs:291:21)
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/yargs/build/index.cjs:1:60678)
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/yargs/index.cjs:5:30)
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/react-native/scripts/generate-specs-cli.js:12:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.0
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by daavidwlf** [comment]
Still having the issue that i can't update the eas-cli. "eas -v" returns:

★ eas-cli@7.2.0 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.
eas-cli/5.9.3 darwin-arm64 node-v21.6.1

I tried all of the above solutions but nothing seems t help.

**Comment by daavidwlf** [comment]
npx eas -v rerturns the correct version. Also when using npx eas <command> everything works as expectet. Does anyone know what's wrong. Do I have two versions of eas-cli installed?

**Comment by nabn** [comment]
still getting this with `npx setup-safari`

**Comment by watert** [comment]
FYI my case: if you install expo-cli in package.json dependencies (like dev deps), and upgrade it to 7.2 with expo 49 may trigger an `config_plugins_1.Updates.getRuntimeVersionNullableAsync is not a function` error.

Just use npm / yarn to uninstall / remove it from deps, and force run cli from global can fix this issue.

**Comment by Vel1khan** [comment]
+1 also having this issue

**Comment by hamzalakrati** [comment]
eas 7.2.0 is working for me!

**Comment by maufernandezdev** [comment]
this command worked for me: **eas build -p ios --non-interactive --skip-credentials-check**

**Comment by d0sc** [comment]
> > > @brentvatne
> > > > fixed in eas-cli@7.2.0 - please update to this version. there was a change on the apple api server side, and this new eas-cli version accounts for this change.
> > > 
> > > 
> > > I uninstalled eas-cli and reinstalled eas-cli@7.2.0 . Unfortunately I'm still getting the same error upon running eas build --profile staging --platform ios . Tried adding `--clear-cache` but it doesn't help.
> > 
> > 
> > can you try `eas --version` what version it shows? also `where eas`
> > also try in `eas` file adding
> > ```
> >   "cli": {
> >     "version": ">= 7.2.0",
> >   },
> > ```
> 
> `npm install -g eas-cli` (to update eas-cli) in combination with this eas.json change resolved the issue for me

I can confirm this worked for me.

**Comment by ashkan-ahmadi** [comment]
I was getting the same error. I ran `npm install -g eas-cli` and that fixed the issue

**Comment by kyallopaw** [comment]
> I was getting the same error. I ran `npm install -g eas-cli` and that fixed the issue

Mine too.

**Comment by lucasbastianik** [comment]
```shell
npm uninstall -g eas-cli
npm install -g eas-cli
```

**Comment by MarceloNascc** [comment]
+1

**Comment by hicodify** [comment]
I just upgraded to the latest version of the CLI and the problem seems to be solved. Thanks!!!!

**Comment by madelineleclair** [comment]
Upgrading to the latest version of the CLI also fixed this for me.

**Comment by AyoCodess** [comment]
> > what work for me and it's so strange is
> > 
> > * reinstall eas yarn global add eas-cli
> > * remove it npm uninstall -g eas-cli
> > * reinstall  again yarn global add eas-cli
> > 
> > Might help someone
> 
> This didn't work for me, however, I reinstalled npm global eas-cli:
> 
> ```
> npm uninstall -g eas-cli
> npm install -g eas-cli
> ```
> 
> after that I just reinstalled node_modules and it worked for me

this worked for me

**Comment by hellotreedigital** [comment]
> thanks, we will investigate this.
> 
> you can use `eas build --non-interactive` to skip the apple auth prompt and used stored app signing credentials to work around this issue for now.
> 
> i'll lock the issue for now so that this comment is easily discoverable, and we'll follow up shortly.

THANK YOU!

**Comment by AnhTP-Corize** [comment]
Reinstall eas-cli worked for me
```
npm uninstall -g eas-cli
npm install -g eas-cli
```

**Comment by woz6622** [comment]
worked again with eas-cli 7.2.0

**Comment by VicOrlands** [comment]
> Reinstall eas-cli worked for me
> 
> ```
> npm uninstall -g eas-cli
> npm install -g eas-cli
> ```

This solved it for me.

**Comment by davidthornton** [comment]
Absolute legends (`npm uninstall`, `rpm install`, however this did cost me 3 identical Android builds 😂)

**Comment by nabn** [comment]
`npx setup-safari` still not working on my end. Can anyone check for me?

**Comment by rahulraoe** [comment]
**npm install -g eas-cli** 
Run this and the cli will be upgraded to 7.3 and that will fix the issue.

**Comment by maxsl89** [comment]
> npm install -g eas-cli

helped!

**Comment by Peek-A-Booo** [comment]
> I was getting the same error. I ran `npm install -g eas-cli` and that fixed the issue

Thanks!

**Comment by emrahyurttutan** [comment]
> thanks, we will investigate this.
> 
> you can use `eas build --non-interactive` to skip the apple auth prompt and used stored app signing credentials to work around this issue for now.
> 
> i'll lock the issue for now so that this comment is easily discoverable, and we'll follow up shortly.

Thanks! @brentvatne @maufernandezdev

**Comment by 123epsilon** [comment]
Running `npm install -g eas-cli` worked for me, does anyone know why this occurs?

**Comment by w8ze-devel** [comment]
Uninstalling & re installing eas-cli (thus installing version 7.3) worked for me too.

**Comment by bitcoinbrisbane** [comment]
i fixed by updating eas.json

```bash
nvm use 18.17.1
npm install -g eas-cli
```

```json
{
  "cli": {
    "version": "7.3.0"
  },
```

**Comment by pradelkai** [comment]
Updating the cli is confirmed working on my end.

**Comment by iAhtasham** [comment]
I am still getting this error on version eas cli 7.3.0, 
Authentication with Apple Developer Portal failed!
Apple provided the following error info:
Service not available because of maintenance activities, please try again after some time.
    Error: build command failed.

**Comment by sendaimono** [comment]
> I am still getting this error on version eas cli 7.3.0, Authentication with Apple Developer Portal failed! Apple provided the following error info: Service not available because of maintenance activities, please try again after some time. Error: build command failed.
> 
> I am still facing the same issue on eas-cli/7.3.0
> 
> PS D:\Projects\React Native> eas --version eas-cli/7.3.0 win32-x64 node-v18.15.0 PS D:\Projects\React Native> eas build --profile production --platform ios Loaded "env" configuration for the "production" profile: no environment variables specified. Learn more: https://docs.expo.dev/build-reference/variables/ √ Using remote iOS credentials (Expo server)
> 
> If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them. This is optional, but without Apple account access you will need to provide all the missing values manually and we can only run minimal validation on them. √ Do you want to log in to your Apple account? ... yes
> 
> › Log in to your Apple Developer account to continue √ Apple ID: ... ************* › Restoring session C:\Users***.app-store\auth*********\cookie › Session expired Local session › The password is only used to authenticate with Apple and never stored on EAS servers Learn more: https://bit.ly/2VtGWhU √ Password (for ************): ... *************** › Saving Apple ID password to the local Keychain Learn more: https://docs.expo.dev/distribution/security#keychain √ Logged in New session Authentication with Apple Developer Portal failed! Apple provided the following error info: Service not available because of maintenance activities, please try again after some time. Error: build command failed.

upgrade to 7.5.0

**Comment by Ty-HA** [comment]
Hello
I got exactly same problem and I can't upgrade to eas 7.6.2, even after uninstall it, I did these 
npm uninstall -g eas-cli
npm cache clean --force
npm install -g eas-cli

But I always got these:
$ eas --version
★ eas-cli@7.6.2 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.

eas-cli/7.3.0 win32-x64 node-v18.17.1

I am stucked with 7.3.0 why ?

I can't build ios "Authentication with Apple Developer Portal failed! Apple provided the following error info: Service not available because of maintenance activities, please try again after some time. Error: build command failed."

**Comment by jadbadran** [comment]
Hi guys, I had the same issue, and the only thing that made it work (in my scenario) was doing `eas login` and logging in my Expo account before logging in my Apple Developer Account on `eas build --profile preview --platform ios` or in my case, it was `eas device:create`. Hope it worked on your ends. Good luck!

**Comment by ismoiliy98** [comment]
Version: `12.5.3`
Getting the same issue.

```
✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.
```

Why does this error happen? Is it on Apple's side or Expo? Isn't there a way to fix it so it will not happen again in new versions?

**Comment by guifischer** [comment]
Version: 12.5.3

Same issue here. Any ideas how to fix it? Happening on build and submit for Apple

**Comment by affcue25** [comment]
Same issue Im receiving since today. It was working fine before. 

`Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.`

**Comment by AroundTheWorld131** [comment]
Facing the same problem! eas-cli@12.5.3

**Comment by billysyt** [comment]
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.

I keep reverting my code and tried so much still no luck. It's in a sudden.

**Comment by Jean-EmmanuelP** [comment]
+1

**Comment by Zakisb** [comment]
Still same issue !

**Comment by bhappen** [comment]
Same issue was occurring on `eas build --platform ios` as well as `eas submit --platform ios`. Updated to eas-cli@12.5.4 and issue is resolved. Try running `npm i -g eas-cli`

**Comment by CllDMR-ekonobi** [comment]
> Same issue was occurring on `eas build --platform ios` as well as `eas submit --platform ios`. Updated to eas-cli@12.5.4 and issue is resolved. Try running `npm i -g eas-cli`

Worked for me. 

+UP

**Comment by Seanmclem** [comment]
the current recommendation is to use `npx eas`, not install `eas-cli`. Or do I have that wrong

**Comment by lucksp** [comment]
> the current recommendation is to use `npx eas`, not install `eas-cli`. Or do I have that wrong

This is the only solution that worked for me

**Comment by CalvinNFT** [comment]
Facing the same issue here, started when I set the `eas.json` distribution property:

```json
  "build": {
    "device": {
      "developmentClient": true,
      "distribution": "internal",
      "ios" : {
        "simulator": false
      }
    },
  }
```

when distribution is set off, problem resolves itself. And yes, I have my iPhone set on developer mode previously had no issues and even has worked with ad-hoc siz months ago. Anyway, I was able to solve my build issue by removing the `distribution` key:

```json
  "build": {
    "device": {
      "developmentClient": true,
      "ios" : {
        "simulator": false
      }
    },
  }
```

My build command is 'npx eas build -p ios --profile device --local' (I use --local for development and our company uses our own infra to build with --local in CI instead of using Expo's cloud builds).

For me the only reason I wanted to distribute was to do ad hoc for my device, but I ended up just crying and doing it through .ipa and [Apple Configurator](https://support.apple.com/apple-configurator) for fast iteration and Testflight for QA and Canary.

**Comment by brentvatne** [comment]
@CalvinNFT - is your apple account the owner of the apple developer team? or what permissions does it have?

**Comment by cognitivestream** [comment]
I asked expo support and their answer was:

> It appears that this issue is currently being discussed within the community, and you can find more information and potential workarounds in this thread: https://github.com/expo/eas-cli/issues/2224

This is an old issue and I don't see any expo devs talking about:
- Is the root cause of this identified
- Is anyone working on fixing the problem? 
- When can we expect a fix=

Instead we get "see if the community has figured out a workaround, or else just dont use our product (which you paid for and build your pipelines around)".

Expo team: Can you do better than that?

**Comment by brentvatne** [comment]
hi @cognitivestream,

The challenge here is that there are a variety of possible ways for this generic error to occur, and many of them are opaque to consumers of this API such as EAS. For example, Apple occasionally changes its endpoints without notice and we then adapt to that by releasing a new version of EAS CLI. However, some folks have slightly incorrect Node installations on their machines, which results in workarounds like having to run `npx eas-cli` instead of `eas` because they are unable to replace an existing `eas-cli` installation with the latest version. This is not an EAS CLI issue, in this case developers should troubleshoot their Node installation to determine why `npm i -g eas-cli` followed by `eas` does not give the latest version, but `npx eas-cli` does. (for example: https://github.com/expo/eas-cli/issues/2224#issuecomment-1943172753)

You mentioned that you do not see any feedback from Expo developers, but if you expand the comments you will see that I responded: https://github.com/expo/eas-cli/issues/2224#issuecomment-1937424905

Commenting on a closed issue is generally not helpful. If you create a new issue where you explain what you are encountering and provide any information that folks would need to help you, then you are far more likely to get help. It's quite possible that you are having the same issue as I referred to above, but you have not verified whether you are in fact actually using the correct EAS CLI version - you can run `eas --version` to very or run `npx eas-cli@latest` to ensure that is what is being used. If you'd like to share more information to help debug, you can run this: `EXPO_APP_STORE_DEBUG=1 eas build -p ios`
