### ISSUE TITLE
Apple Authentication - SMS Broken

### ISSUE THREAD

**Issue by andrewchester1** [expo/eas-cli#2698]
### Summary

When trying to create a new build with eas cli, apple authentication fails when requesting SMS 6 digit pin instead of device. We made sure eas cli is updated. This issue just started showing up yesterday.

### Managed or bare?

managed

### Environment

expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9477386
    npmPackages:
      expo: ~51.0.35 => 51.0.39
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.6 => 0.19.13
    Expo Workflow: managed
    
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✖ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

One or more checks failed, indicating possible issues with the project.

### Error output

√ How do you want to validate your account? ... device / sms

Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

× Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

Run eas cli for an apple build, and request sms for authentication

**Comment by noahkurz** [comment]
I'm seeing this issue as well

**Comment by bmills2023** [comment]
Also having this issue with my project as well

**Comment by andrewchester1** [comment]
Is anyone looking into this issue? It has been three days and multiple people are having the same issue. It doesn't seem like anyone from expo is even looking into this issue.

**Comment by andrewchester1** [comment]
**Here is the output:**

Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

× Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
h [Error]: Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    at t.getAppleResponseError (C:\Users\amchester\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:856515)
    at block (C:\Users\amchester\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:864626)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async j (C:\Users\amchester\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:865138)
    at async T (C:\Users\amchester\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:863991)
    at async t.requestAsync (C:\Users\amchester\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:862469)
    at async t.idmsaRequestAsync (C:\Users\amchester\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:736419)
    at async t.sendRequestTokenToSMSAsync (C:\Users\amchester\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:751279)
    at async y (C:\Users\amchester\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:747910)
    at async y (C:\Users\amchester\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:748254) {
  response: {
    status: 500,
    statusText: '',
    headers: {
      server: 'Apple',
      date: 'Mon, 18 Nov 2024 16:30:28 GMT',
      'content-type': 'application/json;charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'x-apple-i-request-id': '6b90243c-a5ca-11ef-a234-a1a107562366',
      'x-frame-options': 'DENY',
      'x-content-type-options': 'nosniff',
      'x-xss-protection': '1; mode=block',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'content-security-policy': "default-src 'self' ; child-src blob: ; connect-src 'self' https://www.apple.com https://appleid.cdn-apple.com https://webcourier.sandbox.push.apple.com https://xp-qa.apple.com ; font-src 'self' https://www.apple.com https://appleid.cdn-apple.com https://idmsa.apple.com https://gsa.apple.com https://idmsa.apple.com.cn https://signin.apple.com ; frame-src 'self' https://appleid.apple.com https://gsa.apple.com https://account.apple.com ; img-src 'self' https://www.apple.com https://appleid.cdn-apple.com https://*.mzstatic.com data: https://*.apple.com ; media-src data: ; object-src 'none' ; script-src 'self' https://www.apple.com https://appleid.cdn-apple.com https://idmsa.apple.com https://gsa.apple.com https://idmsa.apple.com.cn https://signin.apple.com ; style-src 'unsafe-inline' 'self' https://www.apple.com https://appleid.cdn-apple.com https://idmsa.apple.com https://gsa.apple.com https://idmsa.apple.com.cn https://signin.apple.com ;",
      'referrer-policy': 'origin',
      'x-buildversion': 'R2',
      scnt: 'AAAA-kJDM0VGQ0EyMkI0MkM2RkI1NkM5OTMxM0EyNDE4NEIyN0Q1OEI2QkM5MjJGRDQwNkE5RkREN0YyNjdFMUNEMzIxNjg4Q0I5RDM1RkJGODg1MjJCNjJBQjIyN0YxQzgzNTgyNjJBN0RDQkE1Nzc4RDJDMjgwRUI4MUNDN0VFNTExMzY5MThGNDY1QTExMkQxNzFGRTBENDM1M0JENzEyNzQxRDdDMkM0M0IzRTMwMzhDM0I1NTIxMzYwMEE1RjREOThFMDM1Q0I4QUI0MjJEQzQ0NDNBRDlCMjVFQzYyNjFENDFENTZEOTIyNjZCNEY1RHw0AAABk0AqM6ZhSY67OsJK7TWGDeYCWpdA8S8jT5RXF2pXlK6TRDZl9ks3oMfnGP_TAAq_tGwzuDQprClngANP9oYMgLw7kYKB5dJiFrIGLOGotzrH28SKOA',
      'set-cookie': [Array],
      pragma: 'no-cache',
      expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
      'cache-control': 'no-cache, no-store, no-store',
      'x-apple-id-session-id': 'BC3EFCA22B42C6FB56C99313A24184B27D58B6BC922FD406A9FDD7F267E1CD321688CB9D35FBF88522B62AB227F1C8358262A7DCBA5778D2C280EB81CC7EE51136918F465A112D171FE0D4353BD712741D7C2C43B3E3038C3B55213600A5F4D98E035CB8AB422DC4443AD9B25EC6261D41D56D92266B4F5D',
      'x-apple-auth-attributes': 'xIxE/QYuvTdsqvIiDcwACr+0hUSE+g==',
      'x-apple-id-account-country': 'USA',
      vary: 'accept-encoding',
      'content-language': 'en-US-x-lvariant-USA'
    },
    config: {
      url: 'https://idmsa.apple.com/appleauth/auth/verify/phone',
      method: 'put',
      data: '{"phoneNumber":{"id":1},"mode":"sms"}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      withCredentials: true,
      adapter: [Function (anonymous)],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      jar: [M],
      maxRedirects: 0,
      baseURL: 'https://idmsa.apple.com/',
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 37,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'PUT /appleauth/auth/verify/phone HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: Xcode\r\n' +
        'X-Xcode-Version: 7.0 (7A120f)\r\n' +
        'scnt: AAAA-kJDM0VGQ0EyMkI0MkM2RkI1NkM5OTMxM0EyNDE4NEIyN0Q1OEI2QkM5MjJGRDQwNkE5RkREN0YyNjdFMUNEMzIxNjg4Q0I5RDM1RkJGODg1MjJCNjJBQjIyN0YxQzgzNTgyNjJBN0RDQkE1Nzc4RDJDMjgwRUI4MUNDN0VFNTExMzY5MThGNDY1QTExMkQxNzFGRTBENDM1M0JENzEyNzQxRDdDMkM0M0IzRTMwMzhDM0I1NTIxMzYwMEE1RjREOThFMDM1Q0I4QUI0MjJEQzQ0NDNBRDlCMjVFQzYyNjFENDFENTZEOTIyNjZCNEY1RHwyAAABk0AqJyINhkVhVF8nIEbVBAO7_dM1O0nmuSa6KyxKz1D69xseRis4JOHHE0WzAAofhhIzKOW3Ax9sVZUDyJS0RBjdmLYo36N0b2gg5VGsjb2QmB4chg\r\n' +
        'X-Apple-Id-Session-Id: BC3EFCA22B42C6FB56C99313A24184B27D58B6BC922FD406A9FDD7F267E1CD321688CB9D35FBF88522B62AB227F1C8358262A7DCBA5778D2C280EB81CC7EE51136918F465A112D171FE0D4353BD712741D7C2C43B3E3038C3B55213600A5F4D98E035CB8AB422DC4443AD9B25EC6261D41D56D92266B4F5D\r\n' +
        'X-Apple-Widget-Key: e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42\r\n' +
        'Cookie: myacinfo=DAWTKNV323952cf8084a204fb20ab2508441a07d02d3c36c002f612c60aee274244b57c2e5546367cd5df3aa6e603e149d36b31fbaddc92cb07dc3bc7ed0a86b88825e6ebe55386e49e380b4a0a75953e8f9916dcdf4d884be05151d207638ea41714411946759e53e2a5f391133f6d725436adc3f67dd3f2142136e8f9f9f8ea55085876fe6f5a753d3f4c35d619edecf75075c994ed7d96b5a5e6f6baf4db646a98857968e18740cc58f61a074e6318b91103334d20c6d44d706e928a38d42e24bf1b0af323e619339a2980636be6cd3127a74463a129fee17acf829a83b9a5bfc92c6bc5ef17126b8d8fe5b72910d34f0f072591aa714cb25b95cab41c18ba402e7e2c1a8060d3d05074160749c5c1295b3cca71a734e87a2fcd7b1e1ae7a48f3970d46e9906e7deba29ba1eea002625caad2169a8087e1406b5ae2e883270d0a8d45767689d3af30c54a8ab1bc8b91b9b55c66930547e88d83185e2faeb298e4f5f6a4bc71c15fe43c14f9a7462be188ad65fb728f64710a3c06a52d0803c9c5fcbbbe738b8b576d17db60985b01f6f55a66a806f59e9e79dc03cf786634cf7b14342bca08368fe8451720dd410d0140378aa51c695caaa5d74dab87558ee020c61c1c779ba41c9dd288e539206ad5d0e471adc7de54e4ac9623e65ececd740f2cdd3ca20aa73a972e430e600b3b9e9b67de8018f547373295b0c3822cc56dabfaf5701403f17a6b2a3c8d117f19790e14c21b6f585a47V3; dslang=US-EN; site=USA; aasp=BC3EFCA22B42C6FB56C99313A24184B27D58B6BC922FD406A9FDD7F267E1CD321688CB9D35FBF88522B62AB227F1C8358262A7DCBA5778D2C280EB81CC7EE51136918F465A112D171FE0D4353BD712741D7C2C43B3E3038C3B55213600A5F4D98E035CB8AB422DC4443AD9B25EC6261D41D56D92266B4F5D; acn01=Ow/3ZOYhFQAf3HwPQShRLZBGLFegmuDrX8SeDgbAG3JWT+NqAAofhiTzg/w=\r\n' +
        'Content-Length: 37\r\n' +
        'Host: idmsa.apple.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'PUT',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/appleauth/auth/verify/phone',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'idmsa.apple.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: {
      phoneNumber: [Object],
      securityCode: [Object],
      mode: 'sms',
      type: 'verification',
      authenticationType: 'hsa2',
      autoVerified: false,
      showAutoVerificationUI: false,
      hideSendSMSCodeOption: false,
      supervisedChangePasswordFlow: false,
      supportsRecovery: true,
      hsa2Account: true,
      restrictedAccount: false,
      managedAccount: false,
      serviceErrors: [Array]
    }
  }
}

**Comment by szdziedzic** [comment]
It's best to strip any cookies/session IDs, and so on just in case. You can just post stuff relevant to an error message/error code, without any data that is specific to you like an actual phone number.

**Comment by szdziedzic** [comment]
If it's 500 it seems to be an internal server error on Apple's end 🤔 Based on the error code itself doesn't seem that it's something wrong with the payload that is sent from EAS CLI to Apple servers because then it would be some different error code related to validation error 🤔.

Can you log in to developer.apple.com normally through the website using SMS 2FA?

**Comment by andrewchester1** [comment]
h [Error]: Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    at t.getAppleResponseError (C:\Users\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:856515)
    at block (C:\Users\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:864626)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async j (C:\Users\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:865138)
    at async T (C:\Users\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:863991)
    at async t.requestAsync (C:\Users\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:862469)
    at async t.idmsaRequestAsync (C:\Users\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:736419)
    at async t.sendRequestTokenToSMSAsync (C:\Users\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:751279)
    at async y (C:\Users\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:747910)
    at async y (C:\Users\AppData\Roaming\nvm\v18.18.0\node_modules\eas-cli\node_modules\@expo\apple-utils\build\index.js:1:748254) {
  response: {
    status: 500,
    statusText: '',
    headers: {
      server: 'Apple',
      date: 'Mon, 18 Nov 2024 16:30:28 GMT',
      'content-type': 'application/json;charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'x-apple-i-request-id': xxx,
      'x-frame-options': 'DENY',
      'x-content-type-options': 'nosniff',
      'x-xss-protection': '1; mode=block',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'referrer-policy': 'origin',
      'x-buildversion': 'R2',
      'set-cookie': [Array],
      pragma: 'no-cache',
      expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
      'cache-control': 'no-cache, no-store, no-store',
      'x-apple-id-account-country': 'USA',
      vary: 'accept-encoding',
    },
    config: {
      url: 'https://idmsa.apple.com/appleauth/auth/verify/phone',
      method: 'put',
      data: '{"phoneNumber":{"id":1},"mode":"sms"}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      withCredentials: true,
      adapter: [Function (anonymous)],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      jar: [M],
      maxRedirects: 0,
      baseURL: 'https://idmsa.apple.com/',
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 37,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'PUT /appleauth/auth/verify/phone HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: Xcode\r\n' +
        'X-Xcode-Version: 7.0 (7A120f)\r\n' +
        'Content-Length: 37\r\n' +
        'Host: idmsa.apple.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'PUT',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/appleauth/auth/verify/phone',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'idmsa.apple.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: {
      phoneNumber: [Object],
      securityCode: [Object],
      mode: 'sms',
      type: 'verification',
      authenticationType: 'hsa2',
      autoVerified: false,
      showAutoVerificationUI: false,
      hideSendSMSCodeOption: false,
      supervisedChangePasswordFlow: false,
      supportsRecovery: true,
      hsa2Account: true,
      restrictedAccount: false,
      managedAccount: false,
      serviceErrors: [Array]
    }
  }
}

**Comment by andrewchester1** [comment]
@szdziedzic The entire team can authentication directly to the apple portal with SMS without an issue! I added the Error logs above and cleaned out any sensitive information

**Comment by andrewchester1** [comment]
@szdziedzic have you gotten a chance to look into this issue more? All of our agreements are to up date for Apple. It is concerning that other people are experiencing this issue as well.

**Comment by szdziedzic** [comment]
It's really hard for me to move forward without the reproducible example. I tested auth with multiple Apple accounts I have access to and it always works. Additionally, the error code signals some bug on the Apple end, because it's 500.

Is there any chance you can show me the payload (without sensitive information) sent to Apple servers from your browser when applying the SMS code? We could diff the payload then and see what's different.

**Comment by andrewchester1** [comment]
"~/.app-store/auth/apple-developer-portal-domain.json" is this file in unmanaged expo projects? I am unfamiliar with this file and its location. For the mean time our team has switched from sms verification to device verification and everything is working as expected, but there is a issue

**Comment by szdziedzic** [comment]
This is a file in the `.app-store` folder in your home directory, created by EAS CLI Apple auth utils.

**Comment by andrewchester1** [comment]
I found it. I can test this in 30 minutes, and I'll let you know if this changes anything

**Comment by jameskennethrobinson** [comment]
@szdziedzic for the record, I don't see any `.app-store` folder in my home.

**Comment by szdziedzic** [comment]
>for the record, I don't see any .app-store folder in my home.

Are you using Mac/Linux? 🤔 

>It also seems that only some folks are experiencing this issue? If there was downtime on Apple's part, it seems that issue should be affecting everyone.

We've seen stories in the past that auth was broken only for certain accounts on Apple and it was magically working a few days later because they fixed something on their end. 

It would be helpful if you could compare the payload sent to https://idmsa.apple.com/appleauth/auth/verify/phone when authenticating using the browser vs the payload sent by EAS CLI.

**Comment by jameskennethrobinson** [comment]
@szdziedzic Yes, using MacOS

**Comment by ahmadelafify** [comment]
Any solution??

**Comment by andrewchester1** [comment]
> Any solution??

Sadly no. According to the Expo team this is probably an issue on Apple's side of things. With the amount of traction this issue has been getting, I'm doubtful this is an apple issue, since sms authentication works on the portal without an issue.

**Comment by kylealwyn** [comment]
+1 on the issue and subscribing - will try to post helpful debug info when possible

**Comment by jameskennethrobinson** [comment]
Disappointing! Back to good old Xcode 🤓

**Comment by smisaacs** [comment]
hitting this as well. Changing the url in that file did not work.

**Comment by szdziedzic** [comment]
I asked a couple of people to try to repro this internally, but no luck, unfortunately 😞 

I also manually analyzed the `/appleauth/auth/verify/phone` request sent by EAS CLI and the one sent by the browser. It seems like they match 🤔 Can you try to inspect network traffic and see what request with what payload is made by Apple's web app when authenticating through the browser and selecting SMS 2FA for you? 

I really want to help solve it, but it's tough for me to even understand what's going on if I can't reproduce it on my end.

You can also try to set `EXPO_APP_STORE_DEBUG` to 1 for extra Apple auth debug logs.

**Comment by szdziedzic** [comment]
If I could see what's different between these 2 requests or be able to repro it, it would be really helpful.

**Comment by kylealwyn** [comment]
here are the debug logs from a local eas build. redacted anything potentially identifying. fwiw, it does look like data is coming back in the response.

```
✔ Please select a trusted phone number to send code to › +1 (•••) •••-••42
PUT https://idmsa.apple.com/appleauth/auth/verify/phone
Error: Request failed with status code 500 (PUT https://idmsa.apple.com/appleauth/auth/verify/phone)

Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
h [Error]: Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later

{
  response: {
    status: 500,
    statusText: '',
    headers: {
      server: 'Apple',
      date: 'Fri, 22 Nov 2024 00:20:15 GMT',
      'content-type': 'application/json;charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'keep-alive',
      'x-apple-i-request-id': '***',
      'x-frame-options': 'DENY',
      'x-content-type-options': 'nosniff',
      'x-xss-protection': '1; mode=block',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'content-security-policy': "***",
      'referrer-policy': 'origin',
      'x-buildversion': 'R2',
      scnt: '***',
      'set-cookie': [Array],
      pragma: 'no-cache',
      expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
      'cache-control': 'no-cache, no-store, no-store',
      'x-apple-id-session-id': '***',
      'x-apple-auth-attributes': '***',
      'x-apple-id-account-country': 'USA',
      vary: 'accept-encoding',
      'content-language': 'en-US-x-lvariant-USA'
    },
    config: {
      url: 'https://idmsa.apple.com/appleauth/auth/verify/phone',
      method: 'put',
      data: '{"phoneNumber":{"id":1},"mode":"sms"}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      withCredentials: true,
      adapter: [Function (anonymous)],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      jar: [M],
      maxRedirects: 0,
      baseURL: 'https://idmsa.apple.com/',
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 37,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'PUT /appleauth/auth/verify/phone HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: Xcode\r\n' +
        'X-Xcode-Version: ***' +
        'scnt: ***' +
        'X-Apple-Id-Session-Id: ***' +
        'X-Apple-Widget-Key: ***' +
        'Cookie: ***' +
        'Content-Length: 37\r\n' +
        'Host: idmsa.apple.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'PUT',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/appleauth/auth/verify/phone',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: 'idmsa.apple.com',
      protocol: 'https:',
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: {
      phoneNumber: [Object],
      securityCode: [Object],
      mode: 'sms',
      type: 'verification',
      authenticationType: 'hsa2',
      autoVerified: false,
      showAutoVerificationUI: false,
      hideSendSMSCodeOption: false,
      supervisedChangePasswordFlow: false,
      hsa2Account: true,
      restrictedAccount: false,
      supportsRecovery: true,
      managedAccount: false,
      serviceErrors: [Array]
    }
  }
}```

**Comment by thomas-young1** [comment]
the thing that fixed it for me was just deleting `.app-store` entirely and running the eas command you want again. Guessing something in the `itunes_service_key.txt` was outdated

**Comment by grahamplace** [comment]
Same issue: 
- Reproduced on two different Mac machines, but using the same apple account credential
- `eas-cli/13.4.1`
- Same 500 response shown using debug as others have shared
- Also able to log in via web portal + SMS 2FA without issue
- Tried deleting `.app-store` completely, didn't resolve
- Tried downgrading eas cli version, didn't resolve

**Comment by szdziedzic** [comment]
One more Question: Do you actually receive the authorization code through SMS if this 500 happens?

**Comment by grahamplace** [comment]
> One more Question: Do you actually receive the authorization code through SMS if this 500 happens?

No, in our case the 500 happens after selecting a phone number to use for verification. But the verification code is never sent to that phone number @szdziedzic

**Comment by szdziedzic** [comment]
Oh, okay, thanks for letting me know, it complicates things a bit because my workaround would not work in such a case. I will try to figure out how we can get it to work some other way.

**Comment by brandon-austin-lark** [comment]
Cannot submit a new build to the appstore. I'm on the latest version of the eas-cli

`EXPO_NO_KEYCHAIN=1 EXPO_DEBUG=1 eas submit --platform ios`

```
Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
An unexpected error occurred. - An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/.'. Retrying after 3 seconds (remaining: 3)

✖ Failed to create App Store app PlaySpot
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
An unexpected error occurred. - An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/.
Visit https://appstoreconnect.apple.com and resolve any warnings, then try again.
Submission failed
Error: Submission failed
    at IosSubmitCommand.resolveSubmissionOptionsAsync (/usr/local/lib/node_modules/eas-cli/build/submit/ios/IosSubmitCommand.js:58:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IosSubmitCommand.runAsync (/usr/local/lib/node_modules/eas-cli/build/submit/ios/IosSubmitCommand.js:39:25)
    at async attemptEvent (/usr/local/lib/node_modules/eas-cli/build/submit/submit.js:21:27)
    at async withAnalyticsAsync (/usr/local/lib/node_modules/eas-cli/build/analytics/common.js:7:24)
    at async submitAsync (/usr/local/lib/node_modules/eas-cli/build/submit/submit.js:17:12)
    at async Submit.runAsync (/usr/local/lib/node_modules/eas-cli/build/commands/submit.js:59:32)
    at async Submit.run (/usr/local/lib/node_modules/eas-cli/build/commandUtils/EasCommand.js:68:16)
    at async Submit._run (/usr/local/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/local/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/config/config.js:301:25)
    Error: submit command failed.
```

**Comment by 22adubey** [comment]
> If it's 500 it seems to be an internal server error on Apple's end 🤔 Based on the error code itself it doesn't seem that it's something wrong with the payload that is sent from EAS CLI to Apple servers because then it would be some different error code related to validation error 🤔.
> 
> Can you log in to developer.apple.com normally through the website using SMS 2FA?

Yes I am able to

**Comment by dj-doMains** [comment]
+1 to having this issue as well for the last couple of weeks. I've been able to get around it by adding the `--non-interactive` flag, but I know that is not sustainable.

**Comment by szdziedzic** [comment]
I try to test some changes to the headers we use for Apple auth, can you test if using my fork of CLI `npx -y @szdziedzic/eas-cli@latest build` helps with this issue?

**Comment by bcimbali** [comment]
I have been hitting the same Apple auth errors since last week. 

Anytime I try an `eas build` or `eas device:create`, Apple auth errors out.  

In looking at the`EXPO_APP_STORE_DEBUG` debug logs below, looks like Apple errors out when hitting `POST https://idmsa.apple.com/appleauth/auth/signin/complete`:

```
 EXPO_DEBUG=1 EXPO_NO_KEYCHAIN=1 EXPO_APP_STORE_DEBUG=1 eas device:create
-- Enabled debug logging --
This command lets you register your Apple devices (iPhones, iPads and Macs) for internal distribution of your app.
Internal distribution means that you won't need to upload your app archive to App Store / Testflight.
Your app archive (.ipa) will be installable on your equipment as long as you sign your application with an adhoc provisioning profile.
The provisioning profile needs to contain the UDIDs (unique identifiers) of your iPhones, iPads and Macs.

First of all, choose the Expo account under which you want to register your devices.
Later, authenticate with Apple and choose your desired Apple Team (if your Apple ID has access to multiple teams).

✔ You're inside the project directory. Would you like to use the example-dev account? … yes
› Log in to your Apple Developer account to continue
✔ Apple ID: … email@example.com
› The password is only used to authenticate with Apple and never stored on EAS servers
  Learn more
✔ Password (for email@example.com): … ***********************
› Skip storing Apple ID password in the local Keychain.
⠋ Logging in...GET https://idmsa.apple.com/appleauth/auth/signin?widgetKey=[REDACTED]
⠇ Logging in...200  (GET https://idmsa.apple.com/appleauth/auth/signin?widgetKey=[REDACTED])
POST https://idmsa.apple.com/appleauth/auth/signin/init
⠋ Logging in...200  (POST https://idmsa.apple.com/appleauth/auth/signin/init)
⠙ Logging in...POST https://idmsa.apple.com/appleauth/auth/signin/complete
⠧ Logging in...Error: Request failed with status code 409 (POST https://idmsa.apple.com/appleauth/auth/signin/complete)
✔ Logged in, verify your Apple account to continue
GET https://idmsa.apple.com/appleauth/auth
Error: Request failed with status code 500 (GET https://idmsa.apple.com/appleauth/auth)

Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
h [Error]: Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
```

**Comment by lsnider** [comment]
Had same issue and `EXPO_NO_KEYCHAIN=1` prompted for the SMS verification and allowed the auth to go through.

**Comment by grahamplace** [comment]
FWIW I am now completely unable to log in to App Store connect in Web due to SMS 2FA issues — which makes me think this is more likely an issue on Apple's side than it is an issue with EAS CLI code. 

First noticed the web issue 3 days ago, not sure how long it may have been occurring

![image](https://github.com/user-attachments/assets/158fa300-27a5-416c-b284-1556b93b9935)

**Comment by szdziedzic** [comment]
Regarding the 409 code from this previous request, it's purposefully ignored and swallowed by the CLI because it's the status code that Apple API returns when 2FA is needed. It seems that other services like Fastlane handle it the same way: https://github.com/fastlane/fastlane/blob/1efc837694995d63a3debea753f89af3399b9799/spaceship/lib/spaceship/client.rb#L589-L591

**Comment by davidhollins** [comment]
I have been following this too and have tried every recommendation but get the same error as others.  When I log in to Apple via CLI, it provides 2 numbers for me to select for MFA and as soon as one of those is selected, I receive the same error.  I never get a text to the # selected, just the error.

<img width="1208" alt="eas-cli" src="https://github.com/user-attachments/assets/4c2f6a5b-c642-4589-b684-0e1338c1b91d">

**Comment by bcimbali** [comment]
> I try to test some changes to the headers we use for Apple auth, can you test if using my fork of CLI `npx -y @szdziedzic/eas-cli@latest build` helps with this issue?

Thanks for posting a fork to test a potential fix.

Apologies for the dumb question - to test this fork, do I also need to remove my global `eas-cli`?  Then, run that `npx -y @szdziedzic/eas-cli@latest build` and use the `eas` commands as I did before?

**Comment by davidhollins** [comment]
Tried it with your forked package, still received the same error:

`Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
h [Error]: Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    at t.getAppleResponseError (/Users/johndoe/.npm/_npx/e8a65b59a2b74b16/node_modules/@szdziedzic/apple-utils/build/index.js:1:856515)
    at block (/Users/johndoe/.npm/_npx/e8a65b59a2b74b16/node_modules/@szdziedzic/apple-utils/build/index.js:1:864563)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async O (/Users/johndoe/.npm/_npx/e8a65b59a2b74b16/node_modules/@szdziedzic/apple-utils/build/index.js:1:865075)
    at async I (/Users/johndoe/.npm/_npx/e8a65b59a2b74b16/node_modules/@szdziedzic/apple-utils/build/index.js:1:863928)
    at async t.requestAsync (/Users/johndoe/.npm/_npx/e8a65b59a2b74b16/node_modules/@szdziedzic/apple-utils/build/index.js:1:862464)
    at async t.idmsaRequestAsync (/Users/johndoe/.npm/_npx/e8a65b59a2b74b16/node_modules/@szdziedzic/apple-utils/build/index.js:1:736419)
    at async t.sendRequestTokenToSMSAsync (/Users/johndoe/.npm/_npx/e8a65b59a2b74b16/node_modules/@szdziedzic/apple-utils/build/index.js:1:751279)
    at async y (/Users/johndoe/.npm/_npx/e8a65b59a2b74b16/node_modules/@szdziedzic/apple-utils/build/index.js:1:747910)
    at async m (/Users/johndoe/.npm/_npx/e8a65b59a2b74b16/node_modules/@szdziedzic/apple-utils/build/index.js:1:747207) {
  response: {
    status: 500,
    statusText: '',
    headers: {
      server: 'Apple',
      date: 'Wed, 04 Dec 2024 20:10:59 GMT',
      'content-type': 'application/json;charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'keep-alive',
      'x-apple-i-request-id': 'e099022a-b27b-11ef-a3b3-cd51df75cc5b',
      'x-frame-options': 'DENY',
      'x-content-type-options': 'nosniff',
      'x-xss-protection': '1; mode=block',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'content-security-policy': "default-src 'self' ; child-src blob: ; connect-src 'self' https://www.apple.com https://appleid.cdn-apple.com https://webcourier.sandbox.push.apple.com https://xp-qa.apple.com ; font-src 'self' https://www.apple.com https://appleid.cdn-apple.com https://idmsa.apple.com https://gsa.apple.com https://idmsa.apple.com.cn https://signin.apple.com ; frame-src 'self' https://appleid.apple.com https://gsa.apple.com https://account.apple.com ; img-src 'self' https://www.apple.com https://appleid.cdn-apple.com https://*.mzstatic.com data: https://*.apple.com ; media-src data: ; object-src 'none' ; script-src 'self' https://www.apple.com https://appleid.cdn-apple.com https://idmsa.apple.com https://gsa.apple.com https://idmsa.apple.com.cn https://signin.apple.com ; style-src 'unsafe-inline' 'self' https://www.apple.com https://appleid.cdn-apple.com https://idmsa.apple.com https://gsa.apple.com https://idmsa.apple.com.cn https://signin.apple.com ;",
      'referrer-policy': 'origin',
      'x-buildversion': 'R3',
      scnt: 'AAAA-jg5QjhEQkNENjVFREUxNEY4M0Q5Mjk3NjMxMEI3NUE1MEFGNTUzRTI5N0YwMzQ5RUYzRjBCRTNDREIzNTg0Mjk0RDc4NDRBQkM1QTNFNDIwOUJFRjI0Qjk5QzQ5NkJFNjdFMkFERTU2RkU2Q0I4Q0NGOTk0MDIwQzkxQ0I3MDdFNjM1NzRBRDJCNEYwMDNDNUE4QzU2MjBGRTExQjQ2OTUyODQxMDAzNkVBODMxMzM2QzE4MkVCMzQxMjBBOTdBM0VCQTVEQzAxNUU1RDM5RTJDNzgwMjNBNDU4MEEyODVDQkZGMTQ2OEE2RUE5NUNBN3w0AAABk5NZ2B9OSrf14jGFaGw1CmfdyaWKneCfryUfhcVuclpVjhIithB3Z9zRM1XNABMP3Z0OVoaUj--1XBGIRriKl8eyyIbZfBGDeIm5MCE7SCHknL0bHQ',
      'set-cookie': [Array],
      pragma: 'no-cache',
      expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
      'cache-control': 'no-cache, no-store, no-store',
      'x-apple-id-session-id': '89B8DBCD65EDE14F83D92976310B75A50AF553E297F0349EF3F0BE3CDB3584294D7844ABC5A3E4209BEF24B99C496BE67E2ADE56FE6CB8CCF994020C91CB707E63574AD2B4F003C5A8C5620FE11B469528410036EA831336C182EB34120A97A3EBA5DC015E5D39E2C78023A4580A285CBFF1468A6EA95CA7',
      'x-apple-auth-attributes': 'xrKj/YwXjRs+6a+3PkwAEw/dv13NIA==',
      'x-apple-id-account-country': 'USA',
      vary: 'accept-encoding',
      'content-language': 'en-US-x-lvariant-USA'
    },
    config: {
      url: 'https://idmsa.apple.com/appleauth/auth/verify/phone',
      method: 'put',
      data: '{"phoneNumber":{"id":1},"mode":"sms"}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      withCredentials: true,
      adapter: [Function (anonymous)],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      jar: [M],
      maxRedirects: 0,
      baseURL: 'https://idmsa.apple.com/',
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 37,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'PUT /appleauth/auth/verify/phone HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/json\r\n' +
        'scnt: AAAA-jg5QjhEQkNENjVFREUxNEY4M0Q5Mjk3NjMxMEI3NUE1MEFGNTUzRTI5N0YwMzQ5RUYzRjBCRTNDREIzNTg0Mjk0RDc4NDRBQkM1QTNFNDIwOUJFRjI0Qjk5QzQ5NkJFNjdFMkFERTU2RkU2Q0I4Q0NGOTk0MDIwQzkxQ0I3MDdFNjM1NzRBRDJCNEYwMDNDNUE4QzU2MjBGRTExQjQ2OTUyODQxMDAzNkVBODMxMzM2QzE4MkVCMzQxMjBBOTdBM0VCQTVEQzAxNUU1RDM5RTJDNzgwMjNBNDU4MEEyODVDQkZGMTQ2OEE2RUE5NUNBN3wyAAABk5NZzrr58zU-lvmNZ4TSicfqIF8-CHRbrEirjKpa-Is3jx-yhX-NWYF9zhzRABMFWrHvc37L-6xcePB-GlkMglRqQw1OhXZ4IG1DuPViDnaTReX_UQ\r\n' +
        'X-Apple-Id-Session-Id: 89B8DBCD65EDE14F83D92976310B75A50AF553E297F0349EF3F0BE3CDB3584294D7844ABC5A3E4209BEF24B99C496BE67E2ADE56FE6CB8CCF994020C91CB707E63574AD2B4F003C5A8C5620FE11B469528410036EA831336C182EB34120A97A3EBA5DC015E5D39E2C78023A4580A285CBFF1468A6EA95CA7\r\n' +
        'X-Apple-Widget-Key: e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42\r\n' +
        'Cookie: dslang=US-EN; site=USA; aasp=89B8DBCD65EDE14F83D92976310B75A50AF553E297F0349EF3F0BE3CDB3584294D7844ABC5A3E4209BEF24B99C496BE67E2ADE56FE6CB8CCF994020C91CB707E63574AD2B4F003C5A8C5620FE11B469528410036EA831336C182EB34120A97A3EBA5DC015E5D39E2C78023A4580A285CBFF1468A6EA95CA7; acn01=CqjNxOAETi9WzQTS6OR+AFrlQzEV6jZCZtnByKFQHfg5+v1v0AATBVq8Kyiu\r\n' +
        'User-Agent: axios/0.20.0\r\n' +
        'Content-Length: 37\r\n' +
        'Host: idmsa.apple.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'PUT',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/appleauth/auth/verify/phone',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: 'idmsa.apple.com',
      protocol: 'https:',
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: {
      phoneNumber: [Object],
      securityCode: [Object],
      mode: 'sms',
      type: 'verification',
      authenticationType: 'hsa2',
      autoVerified: false,
      showAutoVerificationUI: false,
      hideSendSMSCodeOption: false,
      supervisedChangePasswordFlow: false,
      enableNonFTEU: false,
      supportsRecovery: true,
      hsa2Account: true,
      restrictedAccount: false,
      managedAccount: false,
      serviceErrors: [Array]
    }
  }
}
    Error: build command failed.`

**Comment by szdziedzic** [comment]
>Apologies for the dumb question - to test this fork, do I also need to remove my global eas-cli? Then, run that npx -y @szdziedzic/eas-cli@latest build and use the eas commands as I did before?

You don't need to remove the global CLI installation 🙌

**Comment by szdziedzic** [comment]
>Tried it with your forked package, still received the same error:

thanks for letting me know

**Comment by JavaScriptJohn** [comment]
I am experiencing this issue as well. The solutions of EXPO_NO_KEYCHAIN=1 and --non-interactive have not worked. This is becoming a serious issue for us.

**Comment by cabhara** [comment]
same issue

**Comment by FreddyJohn** [comment]
Oh sweet! another Expo same issue thread. Let me join! same issues

**Comment by jcapogna** [comment]
I'm hitting this issue as well. Is there any workaround? Kind of surprised to see that such an important part of EAS is broken for so long.

**Comment by Alexandermedia** [comment]
My solution was to get all the credentials needed from the apple certificated page on developer.apple.com and upload those to the credentials section in my project in Expo, then when EAS asked if I wanted to sign in, I said no. Then the build worked.

**Comment by szdziedzic** [comment]
Hey,

We are aware of this issue and take it seriously. These problems are sometimes tricky to debug because our tools make calls to undocumented Apple APIs to ease the process of generating Apple credentials for our users. Unfortunately, these APIs sometimes change without warning, and it breaks some flows in the CLI. It seems like this particular issue is likely caused by a change in the APIs for some accounts, while the flow for the majority of the users works ok as of today. We weren't able to reproduce it internally before, but yesterday we observed the issue on one Apple account that Expo devs have access to. This should allow us to figure it out more quickly. We are testing some patches to our Apple auth libs, but so far it doesn't seem like we have the fix for it. I will keep you updated in this thread.

**Comment by szdziedzic** [comment]
I released version `14.0.1` which includes some improvements to error handling, validation, and auth headers used. You can give it a try but even though it is a good improvement, unfortunately, it doesn't seem to resolve the main issue in our internal testing.

**Comment by JavaScriptJohn** [comment]
Thanks, you're correct, not resolving on my end. Better error messages though: 

`Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.`

**Comment by bcimbali** [comment]
Thanks for the quick update. I just upgraded my `eas-cli` to `14.0.2`, got rid of my local `.app-store`, logged out, re-logged in, and hit the same improved error message as above:
```
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.
```

I just double-checked my work Apple account I'm using for my EAS CLI and it does have 2FA set up with the correct phone number.  

Not sure if it's a common thread with other users hitting this error but my work Apple account is tied to my work email and that Apple account doesn't have my phone number listed in its Apple account's `"Email & Phone Number"` section. This is because my phone number is tied to my personal Apple account and can only be used with one Apple account.  That said, my phone number is still listed in the Apple account's 2FA section and has worked just fine in the past.

**Comment by j0pp** [comment]
> Thanks for the quick update. I just upgraded my `eas-cli` to `14.0.2`, got rid of my local `.app-store`, logged out, re-logged in, and hit the same improved error message as above:
> 
> ```
> Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
> - Verification codes can’t be sent to this phone number at this time. Please try again later.
> ```
> 
> I just double-checked my work Apple account I'm using for my EAS CLI and it does have 2FA set up with the correct phone number.
> 
> Not sure if it's a common thread with other users hitting this error but my work Apple account is tied to my work email and that Apple account doesn't have my phone number listed in its Apple account's `"Email & Phone Number"` section. This is because my phone number is tied to my personal Apple account and can only be used with one Apple account. That said, my phone number is still listed in the Apple account's 2FA section and has worked just fine in the past.

I have the same situation: work email is used for the Apple account I am signing into w/ my personal number as my 2FA (which is associated with a different, personal Apple account).

Encountering the same issues on `14.0.2`.

**Comment by jcapogna** [comment]
Same for me. Upgraded to 14.0.2 and seeing the same improved error message. I'm also using my personal phone number for 2FA on my work Apple account

**Comment by bcimbali** [comment]
@jnnnthnn - That just worked for me!  I logged out of my personal Apple account on my work computer, logged into my work Apple account, ran an `eas logout` in CLI, logged in via the EAS CLI, and was able to run a `eas device:create` this time.

It used to work with me signed into my personal Apple account on my computer.  Nonetheless, this solved it for me 🙌

**Comment by nickdep217** [comment]
I created a user on my Mac with the same Apple ID that I used on the app store account. I was able to sign in without using sms and successfully submit the build. I recommend turning on "Fast User Switching in Control Center" so you can switch between accounts on Mac

**Comment by JayOfemi** [comment]
I am also running into this issue.

I saw a similar issue on Apple forums where a user was not receiving 2fa messages at all. The recommended solution was to call the wireless carrier and have them "refresh"/"re-sync" your phone on the network. I have not tried this, but I can confirm that I am receiving 2fa text messages when logging into the same Apple dev account on the web. Yet, I get the below error when attempting an eas build.

```
× Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.
``` 

This is a major problem for us as we are now unable to build and submit to the store and we are on a time crunch to release a new version of our app.

Any updates on this would be much appreciated..

**Comment by JayOfemi** [comment]
I was just able to get around this by logging into my apple account on my mac (as some stated above). Although it did not fix the issue with 2fa via sms, but now that at least 1 device is tied to this apple account, I went back to my PC where I am attempting the build, and was now able to select the "device" option in eas cli, which did work to show me the 2fa code on my mac. We can now perform a build with this workaround but it would still be nice to have the sms option working again.

**Comment by oogunjob** [comment]
Having the same issue still @JayOfemi

**Comment by Dhivas-Sugumar** [comment]
Having the same issue as well. Was able to resolve this by logging into the apple account associated with the Apple developer account. Not ideal, but a quick workaround. Would be great to have a permanent fix!

**Comment by JavaScriptJohn** [comment]
> Having the same issue as well. Was able to resolve this by logging into the apple account associated with the Apple developer account. Not ideal, but a quick workaround. Would be great to have a permanent fix!

For the record I have done this multiple times and it has not fixed my issue.

**Comment by tmeduho** [comment]
same issue here

**Comment by szdziedzic** [comment]
>We were running into this same issue when trying to use work Apple accounts tied to our personal phone numbers. We were able to get around the issue by logging into those Apple accounts directly via systems settings on our macOS machines and running eas again.

Just to make sure I understand it correctly - you started to use the `device` 2FA method using your Mac as the selected device, right? It's not like the SMS method started to work after you did it, correct?

**Comment by szdziedzic** [comment]
From our observations, it seems to only occur for American phone numbers for now. Let me know if this observation isn't correct.

**Comment by szdziedzic** [comment]
When it comes to the affected account we have access to internally (mentioned [here](https://github.com/expo/eas-cli/issues/2698#issuecomment-2522780263)), we were able to see that there are some headers different in the requests done via the website and ones done through CLI. We are trying to find the right combination of headers to fix the issue, but the bad thing is that we can only try different requests 4 times before getting locked out. It makes it pretty hard to fix.

**Comment by szdziedzic** [comment]
We've just published [`14.0.3`](https://github.com/expo/eas-cli/releases/tag/v14.0.3) with the fix to this problem. Can you please confirm that it works for you as well on the `latest` version? 🙏

**Comment by JavaScriptJohn** [comment]
Still not working for me

eas -v
eas-cli/14.0.3 linux-x64 node-v18.20.4

Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.
    Error: build command failed.

**Comment by tmeduho** [comment]
Unfortunately I'm still receiving the same error on 14.0.3

> ✔ Please select a trusted phone number to send code to › +1 ...
> 
> Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
> - Verification codes can’t be sent to this phone number at this time. Please try again later.'. Retrying after 3 seconds (remaining: 3)
> 
> ✖ Logging in...
> Authentication with Apple Developer Portal failed!
> Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
> - Verification codes can’t be sent to this phone number at this time. Please try again later.
>     Error: build command failed.

**Comment by EvanBacon** [comment]
I was able to reproduce the issue before (American phone number, located in America) and can confirm that `eas-cli/14.0.3 darwin-arm64 node-v20.12.2` works. This shouldn't be needed, but you can try clearing the local auth caches on your computer with `rm -rf ~/.app-store/`, and signing in again.

**Comment by tmeduho** [comment]
> I was able to reproduce the issue before (American phone number, located in America) and can confirm that `eas-cli/14.0.3 darwin-arm64 node-v20.12.2` works. This shouldn't be needed, but you can try clearing the local auth caches on your computer with `rm -rf ~/.app-store/`, and signing in again.

Okay this is good actually, I did get it to work when using node 20..

**Comment by JavaScriptJohn** [comment]
eas-cli/14.0.3 linux-x64 node-v20.18.1

> > I was able to reproduce the issue before (American phone number, located in America) and can confirm that `eas-cli/14.0.3 darwin-arm64 node-v20.12.2` works. This shouldn't be needed, but you can try clearing the local auth caches on your computer with `rm -rf ~/.app-store/`, and signing in again.
> 
> Okay this is good actually, I did get it to work when using node 20..

Still not working for me: 
eas-cli/14.0.3 linux-x64 node-v20.18.1

**Comment by tmeduho** [comment]
Actually, where I'm getting stuck now is switching providers

**Comment by ateethk** [comment]
It's working now for me on node v22.12.0 and eas-cli/14.0.3

**Comment by TrevPennington** [comment]
Would not work on eas-cli/14.0.3 for me. Downgraded to 14.0.0 and it works

**Comment by alimek** [comment]
14.0.3 solved problem with `eas build` for me, but i still getting error when `eas submit` for stores.

**Comment by szdziedzic** [comment]
@alimek can you try to do `rm -rf ~/.app-store/` to clear the cache?

**Comment by alimek** [comment]
> @alimek can you try to do `rm -rf ~/.app-store/` to clear the cache?

Tried, asking for device/sms verification (tried both - device and sms) and still getting same issue.

Same error was for `eas build` and last version of `eas-cli` solved it, i am pretty sure I am admin in the Team so I dont think so its problem with my account.

**Comment by willhamilton24** [comment]
Same issue, going to try messing with the version.

**Comment by FreddyJohn** [comment]
Yeah, really deeply need this fixed, can't add new provision profile changes and cannot push to App Stores, this is blocking our release date. Please fix this quickly

**Comment by JavaScriptJohn** [comment]
I was able to get it working by taking one of my test apple devices and logging in under the same apple credentials I use for eas. When I did an EAS build it asked me if i wanted to use 2fa from my device and it worked. 

For the record, I don't condone this fix because it required an apple device.

**Comment by brentvatne** [comment]
> 14.0.3 solved problem with `eas build` for me, but i still getting error when `eas submit` for stores.
> 
> ```
> ✔ Apple ID: … XXXX
> › Restoring session /Users/alimek/.app-store/auth/XXX/cookie
> › Session expired Local session
> › Using password for XXX from your local Keychain
>   Learn more: https://docs.expo.dev/distribution/security#keychain
> ✔ Logged in New session
> ✔ Select a Team › XXX
> ✔ Select a Provider › XXX
> ✖ Couldn't switch to provider XXX
> Authentication with Apple Developer Portal failed!
> Apple 401 detected - You are either not logged in, your account doesn't have access to the requested data, or the page doesn't exist
> Submission failed
> ```

can you clear the `~/.app-store` directory and retry?

**Comment by brentvatne** [comment]
if you are encountering any issues related to those discussed in this thread, please do the following, in order:

1. update to the latest eas-cli: `npm i -g eas-cli` (or the equivalent for whatever pkg manager you use)
2. verify you are using the latest eas-cli: `eas -v` - this should be 14.1.0 or greater
3. delete `~/.app-store` (eg: `rm -rf ~/.app-store`) (on windows, this should be: `C:\Users\YourUsername\.app-store`)
4. try building again
