### ISSUE TITLE
V15 breaks EAS build (Path is a directory: rm returned EISDIR (is a directory))

### ISSUE THREAD

**Issue by benjaminkomen** [expo/eas-cli#2883]
### Summary

All our builds fail since version 15.0.0 of eas-cli was released.

### Managed or bare?

managed

### Environment

```
 expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.2 - ~/.nvm/versions/node/v20.18.2/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.2 - /opt/homebrew/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 30, 31, 33, 34, 35
        Build Tools: 30.0.3, 33.0.1, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23726.103.2422.12816248
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 14.7.1
      expo-cli: 6.3.7
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Our GitHub Actions workflow that creates EAS builds is failing since yesterday, after version 15.0.0 was published:

```
Run expo/expo-github-action/preview@v8
  with:
    command: eas build --profile preview --platform all --non-interactive --no-wait
    comment: true
    working-directory: /home/runner/work/[REDACTED]
    github-token: ***
  env:
    EXPO_TOKEN: ***
    output_type: merge
    COMMIT_NUMBER: 101[REDACTED]
/opt/hostedtoolcache/eas-cli/15.0.4/x64/node_modules/.bin/eas --version
eas-cli/15.0.4 linux-x64 node-v22.1[3](REDACTED).1
Run eas build --profile preview --platform all --non-interactive --no-wait --json"
  /opt/hostedtoolcache/eas-cli/15.0.[4](https://github.com/]REDACTED]/actions/runs/13164343981/job/36741321345#step:10:4)/x64/node_modules/.bin/eas build --profile preview --platform all --non-interactive --no-wait --json
  (node:208[5](https://github.com/[REDACTED]/actions/runs/13164343981/job/36741321345#step:10:5)) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
  (Use `node --trace-deprecation ...` to show where the warning was created)
  Environment variables with visibility "Plain text" and "Sensitive" loaded from the "preview" environment on EAS: REDACTED
  Environment variables loaded from the "preview" build profile "env" configuration: APP_ENV.
  
  
  🤖 Android build
  ✔ Using remote Android credentials (Expo server)
  ✔ Using Keystore from configuration: Build Credentials s8YdA-k0ko (default)
  
  Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
  Failed to upload the project tarball to EAS Build
  
  Reason: Path is a directory: rm returned EISDIR (is a directory) /tmp/runner/eas-cli-nodejs/df2507eb-eeb9-4da2-804d-49a8[6](https://github.com/[REDACTED]/actions/runs/13164343981/job/36741321345#step:10:6)fd50070-shallow-clone/blitz
      Error: build command failed.
Error: Could not create a new EAS Update
```

We have a git submodule in our project, called `blitz`. This is the contents of our `.gitmodules` file:
```
[submodule "blitz"]
	path = blitz
	url = git@github.com:[REDACTED]/blitz.git
```

We have this in our `.gitignore`, without a slash behind it:
```
[...]
# build artifacts
*.app
*.ipa
*.apk
*.aab
*.tar.gz
blitz
*.zip
[...]
```

And also in our `.easignore`, with a slash behind it:
```
# Ignore unnecessary files/folders
.expo/
.git/
.github/
.husky/
.idea/
.maestro/
.storybook/
blitz/
```

I think the error comes from the way we have it in our `.gitignore` ? I will try to add a slash and see if that resolves it.

**Comment by sjchmiela** [comment]
Hey @benjaminkomen, sorry. https://github.com/expo/eas-cli/pull/2884 should fix this. The error was coming from how we're processing files returned by `git ls-files` to remove based on `.easignore` rules. It was using a plain `rm` instead of `rm -rf` and it turns out submodules are returned by Git as single entries.

**Comment by benjaminkomen** [comment]
Thanks for the quick fix, we pinned to version 14.7.1 of eas-cli for now, but will test your fix once it is released.

**Comment by benjaminkomen** [comment]
Just tried locally:
```
npm install -g eas-cli@15.0.5
eas build --profile development_device --platform android --message test --local local
```

And the issue is resolved, thanks again!

**Comment by Elozino** [comment]
I still experience the same issue on v15

Build project compression jumped from 6.4mb to 310mb

After debugging I realised that the  node_moudles was also being compressed in v15
