### ISSUE TITLE
Issue Authenticating with apple

### ISSUE THREAD

**Issue by cSieves** [expo/eas-cli#3047]
### Summary

Every time I try to do an apple build using the eas cli I get the following error; 

```Authentication with Apple Developer Portal failed!
Cannot extract key "teams" from response data of type string:```

The command I am running is 

```eas build --profile production --platform ios```

### Managed or bare?

Managed

### Environment

  expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.18.0 - ~/Garreth-Social-Media/frontend/node_modules/.bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 10.9.2 - /usr/local/bin/npm
      Watchman: 2025.04.28.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0 => 52.0.7 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    npmGlobalPackages:
      eas-cli: 12.6.2
      expo-cli: 6.3.12
    Expo Workflow: managed


### Error output

```Authentication with Apple Developer Portal failed!
Cannot extract key "teams" from response data of type string:```

### Reproducible demo or steps to reproduce from a blank project

Running ```eas build --profile production --platform ios```

**Comment by ddavyd0v** [comment]
Also affected

**Comment by ovsen** [comment]
Apple status says that maintenance is complete but the returned page says maintenance is still ongoing?

**Comment by ovsen** [comment]
This is now working for me, maybe worth re-testing and closing out @cSieves

**Comment by DuzakhNX** [comment]
This is fixed by simply going to the Apple Developer website with the team admin and accepting the new terms and conditions.

**Comment by timstoute** [comment]
Yup, working for me too now.  I was still experiencing this issue AFTER  going to the Apple Developer website with the team admin and accepting the new terms and conditions.  But it is working for me this morning.

**Comment by cSieves** [comment]
Also working for me now! Closing
