### ISSUE TITLE
--type flag not being picked up

### ISSUE THREAD

**Issue by delanebob** [expo/eas-cli#591]
Hi, we recently upgraded to v0.25 of the cli but when running it in minimal mode, it doesn't seem to pick up the `--type` flag anymore, unless there is a new requirement that I've missed in the docs/cli help? I've went back through the versions and it seems the v0.23 is the latest version to work as expected.

**Reproduce**
`eas submit --platform=android --key=GoogleAppAuthKey.json --type=aab --url=https://expo.dev/artifacts/XXXXXXXXXX`

**Actual Result**
`We couldn't auto detect the archive type` and changes to interactive mode.

**Expected Result**
Continue in minimal mode

**CLI Version**
`eas-cli/0.25.0 darwin-x64 node-v12.13.1`

**Comment by dsokal** [comment]
Hi, 
I think I can confirm this is a bug. Fortunately, we'll soon deprecate the `--type` flag (probably sometime next week). The archive type detection is going to happen on the server-side.

**Comment by delanebob** [comment]
Thanks for letting us know @dsokal.

We have hardcoded the version to v0.23 for now to fix our build pipeline. Would you mind keeping us updated and letting us know when it's completed. We can then test it out from our side?

**Comment by dsokal** [comment]
Sure, when the fix is released I'll let you know :)

**Comment by DomVinyard** [comment]
> We have hardcoded the version to v0.23 for now to fix our build pipeline

How does this fix the build pipeline? Could you elaborate a little please, we still have this problem

**Comment by dsokal** [comment]
@delanebob  Hi, this should be fixed in `eas-cli@0.26.0` Could you please let me know if the issue goes away after the upgrade?

**Comment by delanebob** [comment]
@dsokal I'm off work this week. But will give it a try next Monday and get back to you 👍

**Comment by delanebob** [comment]
> > We have hardcoded the version to v0.23 for now to fix our build pipeline
> 
> How does this fix the build pipeline? Could you elaborate a little please, we still have this problem

@DomVinyard we use Jenkins for our build pipeline. The issue we were having was that Jenkins can't run in interactive mode and we have to tell it the android type by using the `--type` flag.

v0.25 didn't seem to be picking it up when I passed it in. So I went back through the versions by running `yarn global add eas-cli@0.23` and tried to see what was the newest version that worked with the `--type` flag.

So in our Jenkins pipeline I hard coded the version in a similar way so it would use that version and successfully submit it to the Play Store. Let me know if I have missed any other details @DomVinyard.
