### ISSUE TITLE
iOS build with expo-document-picker for internal distribution fails because of unsupported entitlement

### ISSUE THREAD

**Issue by colinux** [expo/eas-cli#693]
### Summary

In managed workflow on SDK 43 with `expo-document-picker`, fastlane fails in a profile having `distribution: internal` because of unsupported `icloud-container-environment` entitlement.

### Environment

```
EAS CLI 0.32.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 16.11.1 - /usr/local/opt/node/bin/node
      Yarn: 3.0.2 - ~/.npm-packages/bin/yarn
      npm: 8.0.0 - /usr/local/bin/npm
    Utilities:
      Git: 2.29.2 - /usr/local/bin/git
    npmPackages:
      expo: next => 43.0.0-beta.3
      expo-dev-client: ~0.6.2 => 0.6.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.32.0
      expo-cli: 4.12.1
```

### Error output

> Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided}

It's working _without_ `distribution: internal` (I don't know why?)

### Reproducible demo or steps to reproduce from a blank project

What I've tried, with the same error :

- Manually adding `ios.entitlements` entry with `'com.apple.developer.icloud-container-environment': 'Production'` in `app.config.js` (seems ignored by EAS)
- `EXPO_NO_CAPABILITY_SYNC=1 eas build`
- `EXPO_DEBUG=1 eas build` says `Skipping entitlement that is not supported by EAS: com.apple.developer.icloud-container-environment` 

This last step led me to https://github.com/expo/eas-cli/blob/1419ca6325268ab1bd3f45ed7fcf0a5985ac5552/packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts#L258 which doesn't contain `com.apple.developer.icloud-container-environment` in CapabilityMapping definitions.

See entitlement details https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_icloud-container-environment

Here is a failing build
https://expo.dev/accounts/dacotha/projects/imparato/builds/53aaae68-3e0f-4c78-86d7-757ccc8083e4

**Comment by EvanBacon** [comment]
The bundleIdCapabilities only updates entitlements that have some API endpoint in Apple, this doesn't appear to be the case in `com.apple.developer.icloud-container-environment` so eas-cli should skip it. Many keys are skipped. Generally, we only need to perform remote registration for capabilities that can be set directly through Xcode.

When EAS misses a capability that was in fact required to be registered in Apple servers the xcodebuild error will be close to the start of the process and look something like this ([cite](https://github.com/expo/eas-cli/pull/384)):
```
❌  error: Provisioning profile "*[expo] com.bacon.yolo22 AppStore 2021-05-04T22:29:48.816Z" doesn't support the Associated Domains capability. (in target 'yolo22' from project 'yolo22')

❌  error: Provisioning profile "*[expo] com.bacon.yolo22 AppStore 2021-05-04T22:29:48.816Z" doesn't include the com.apple.developer.associated-domains entitlement. (in target 'yolo22' from project 'yolo22')
```

Your error however, looks to be thrown at the end of the archive step (which is a frustrating time for xcode to perform validation), and it looks like:

```
error: exportArchive: exportOptionsPlist error for key "iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided
Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided}
```

It seems that the issue is related to the "exportOptionsPlist" which needs to have `iCloudContainerEnvironment` added to the plist file.

In Fastlane, this is done by adding `export_options({iCloudContainerEnvironment: 'Development'})` to the Gymfile. Will follow up with the team on how this can be done via eas-cli.

**Comment by TomasSestak** [comment]
Hello, i saw you merged a fix, how can i use it please?

**Comment by TomasSestak** [comment]
Could you help me solving this in bare workflow please? i tried to set it in
projectname.entitlements but without success

**Comment by TomasSestak** [comment]
Thank you, it works now

**Comment by stripuramallu3** [comment]
For anyone who runs into this issue. The fix went into _expo-document-picker_ version 10.1.0, but running _expo install expo-document-picker_ installs 10.0.3. Upgrading to 10.1.0 fixes the issue. I believe 10.1.0 is set to be a part of Expo SDK 44 release.

**Comment by louisholley** [comment]
this is still happening for me with the latest `eas-cli` and latest `expo-document-picker`. can anyone assist?

**Comment by andrija29** [comment]
@EvanBacon Still happening in 10.1.0 and latest eas-cli.

**Comment by kbrandwijk** [comment]
> For anyone who runs into this issue. The fix went into _expo-document-picker_ version 10.1.0, but running _expo install expo-document-picker_ installs 10.0.3. Upgrading to 10.1.0 fixes the issue. I believe 10.1.0 is set to be a part of Expo SDK 44 release.

If you are on SDK 44, then `expo install` will install version `~10.1.0`. SDK 43 on the other hand is officially compatible with version `~10.0.3`, so `expo install` will _not_ install 10.1.x automatically. Using 10.1.x with SDK 43 (if that's the case for you) _might_ work fine, but as SDK 43 has not been explicitly tested against that version, we don't install it by default.

**Comment by kbrandwijk** [comment]
> this is still happening for me with the latest `eas-cli` and latest `expo-document-picker`. can anyone assist?

As I've understood from the other thread you linked, your issue has already been solved by now after updating?

**Comment by phatmann** [comment]
I am still seeing this issue. I am using expo-document-picker 10.1.3.

**Comment by floki-92** [comment]
Same issue here with expo-document-picker 10.1.3

**Comment by phatmann** [comment]
What fixed it for me was adding [iCloudContainerEnvironment](https://github.com/expo/expo/blob/main/packages/expo-document-picker/plugin/src/withDocumentPickerIOS.ts#L12) to the expo-document-picker plugin parameters in app.json per [this comment](https://github.com/expo/eas-cli/issues/1022#issuecomment-1069149766).

For example:
```
"plugins": [
      [
        "expo-document-picker",
        {
          "appleTeamId": TEAM_ID,
          "iCloudContainerEnvironment": "Production"
        }
      ]
],
```

**Comment by floki-92** [comment]
@phatmann: thanks for letting me know. I' test it :)

**Comment by tichopad** [comment]
> What fixed it for me was adding [iCloudContainerEnvironment](https://github.com/expo/expo/blob/main/packages/expo-document-picker/plugin/src/withDocumentPickerIOS.ts#L12) to the expo-document-picker plugin parameters in app.json per [this comment](https://github.com/expo/eas-cli/issues/1022#issuecomment-1069149766).
> 
> For example:
> 
> ```
> "plugins": [
>       [
>         "expo-document-picker",
>         {
>           "appleTeamId": TEAM_ID,
>           "iCloudContainerEnvironment": "Production"
>         }
>       ]
> ],
> ```

Adding `iCloudContainerEnvironment` fixed the issue for me.

**Comment by youssdevx** [comment]
> What fixed it for me was adding [iCloudContainerEnvironment](https://github.com/expo/expo/blob/main/packages/expo-document-picker/plugin/src/withDocumentPickerIOS.ts#L12) to the expo-document-picker plugin parameters in app.json per [this comment](https://github.com/expo/eas-cli/issues/1022#issuecomment-1069149766).
> 
> For example:
> 
> ```
> "plugins": [
>       [
>         "expo-document-picker",
>         {
>           "appleTeamId": TEAM_ID,
>           "iCloudContainerEnvironment": "Production"
>         }
>       ]
> ],
> ```

It fixed the issue for me, thanks! Please update the documentation: https://docs.expo.dev/versions/latest/sdk/document-picker/

**Comment by kennethlynne** [comment]
appleTeamId should not be included AFAIK reading [the source](https://github.com/expo/expo/blob/main/packages/expo-document-picker/plugin/src/withDocumentPickerIOS.ts#L11)

```
// app.config.ts
const environment = 'development'
...
'plugins': [
      [
        'expo-document-picker',
        {
          'iCloudContainerEnvironment': environment === 'production' ? 'Production' : 'Development'
        }
      ]
],
...
```

**Comment by b0n1q** [comment]
Is anybody has this issue?

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "iCloudContainerEnvironment": value "Development" is not allowed" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "iCloudContainerEnvironment": value "Development" is not allowed}

**Comment by andresespinosapc** [comment]
> What fixed it for me was adding [iCloudContainerEnvironment](https://github.com/expo/expo/blob/main/packages/expo-document-picker/plugin/src/withDocumentPickerIOS.ts#L12) to the expo-document-picker plugin parameters in app.json per [this comment](https://github.com/expo/eas-cli/issues/1022#issuecomment-1069149766).
> 
> For example:
> 
> ```
> "plugins": [
>       [
>         "expo-document-picker",
>         {
>           "appleTeamId": TEAM_ID,
>           "iCloudContainerEnvironment": "Production"
>         }
>       ]
> ],
> ```

This does not solve the problem for me 😢 . These are the versions of my packages:
```
eas-cli@3.7.2
expo@46.0.20
expo-document-picker@10.3.0
```

I also has `ios.usesIcloudStorage` set to true, also tried setting it to false.

If I remove `expo-document-picker` from my project the error is gone though, I don't understand what could be happening.

**Comment by andresespinosapc** [comment]
Is there any way I can debug this problem?

**Comment by phatmann** [comment]
@andresespinosapc what is your exact error? If you are on a Mac, have you tried doing a local build in order to see the exact issue?

**Comment by phatmann** [comment]
@andresespinosapc If you make a local build, you can examine the archive file to see what entitlements were added to it. This is how I debugged the issue and found a fix.

I am surprised you are getting this error, since the plugin config setting I recommended specifically adds this entitlement. Are you sure that your app config is correct and is being used?

**Comment by CodySwannGT** [comment]
> 



> > What fixed it for me was adding [iCloudContainerEnvironment](https://github.com/expo/expo/blob/main/packages/expo-document-picker/plugin/src/withDocumentPickerIOS.ts#L12) to the expo-document-picker plugin parameters in app.json per [this comment](https://github.com/expo/eas-cli/issues/1022#issuecomment-1069149766).
> > For example:
> > ```
> > "plugins": [
> >       [
> >         "expo-document-picker",
> >         {
> >           "appleTeamId": TEAM_ID,
> >           "iCloudContainerEnvironment": "Production"
> >         }
> >       ]
> > ],
> > ```
> 
> This does not solve the problem for me 😢 . These are the versions of my packages:
> 
> ```
> eas-cli@3.7.2
> expo@46.0.20
> expo-document-picker@10.3.0
> ```
> 
> I also have `ios.usesIcloudStorage` set to true, also tried setting it to false.
> 
> If I remove `expo-document-picker` from my project the error is gone though, I don't understand what could be happening.

remove `usesIcloudStorage`

**Comment by buzzreminder** [comment]
> What fixed it for me was adding [iCloudContainerEnvironment](https://github.com/expo/expo/blob/main/packages/expo-document-picker/plugin/src/withDocumentPickerIOS.ts#L12) to the expo-document-picker plugin parameters in app.json per [this comment](https://github.com/expo/eas-cli/issues/1022#issuecomment-1069149766).
> 
> For example:
> 
> ```
> "plugins": [
>       [
>         "expo-document-picker",
>         {
>           "appleTeamId": TEAM_ID,
>           "iCloudContainerEnvironment": "Production"
>         }
>       ]
> ],
> ```

This solution works!  UDAMAN
