### ISSUE TITLE
eas build -p ios is failing at Install Dependencies stage.

### ISSUE THREAD

**Issue by koukoujohn** [expo/eas-cli#907]
### Build/Submit details page URL

https://expo.dev/accounts/agtheodorides/projects/orders_staging/builds/eaae7fde-365d-4f18-b99b-637b79ed973f

### Summary

It looks like something is wrong with running npm during this stage(eas build android builds succesfully the exact same commit)

Normally in previous succesful builds I see in the Install Dependencies logs these lines after Running npm in the root dir of your repository  -->

> fsevents@1.2.13 install /Users/expo/workingdir/build/node_modules/chokidar/node_modules/fsevents
> node install.js

- Now I see this:
[stderr] npm

- And then a bunch of similar stderr of this type:
WARN tar ENOENT: no such file or directory, open '/Users/expo/workingdir/build/node_modules/.staging/caniuse-lite-0ad8bd02/data/regions/BB.js'
[stderr] npm WARN

### Managed or bare?

Managed

### Environment

EAS CLI 0.44.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.33.0. - /mingw64/bin/git
    npmPackages:
      expo: ^44.0.4 => 44.0.4
      expo-dev-client: ~0.8.0 => 0.8.0
      expo-updates: ~0.11.3 => 0.11.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.4.4 => 4.4.4
    Project workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Nothing just try to create an iOS build with a blank project it fails at install dependencies not at fastlane

**Comment by koukoujohn** [comment]
Never mind. removing node modules and package-lock.json and reinstalling with npm i fixed it

**Comment by AdeelKahan** [comment]
i try to remove node modules and package-lock.json then npm i but this issue still occure
